import {mountEditorConsole} from './editor-console.js';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initialTex=String.raw`\documentclass[11pt]{article}
\usepackage{graphicx}
\title{Learning to Reach, Together}
\author{Research team}
\begin{document}
\maketitle

\begin{abstract}
We study whether shared representations improve
sample efficiency for two-arm manipulation.
Pretraining improves validation loss in this
illustrative comparison. Real-world evaluation
is needed to establish transfer.
\end{abstract}

\section{Method}
We compare a pretrained visual encoder against
a model trained from scratch. Both methods use
the same split, optimizer, and training budget.
We report training and validation loss on the
same step axis, with no test-set tuning.

\section{Results}
The pretrained model converges faster and has
lower validation loss in these sample curves.
The gap motivates a controlled evaluation,
rather than a claim about real-world success.

\section{Next steps}
Evaluate both methods on held-out scenes.
Report uncertainty across three seeds and
inspect failures before expanding the study.
\end{document}`;
const beforeCode=`import wandb\n\n\ndef log_metrics(step, train_loss, val_loss):\n    """Publish metrics from one training step."""\n    wandb.log({"train/loss": train_loss}, step=step)\n\n\ndef train(model, batches, validation):\n    for step, batch in enumerate(batches):\n        train_loss = model.update(batch)\n        val_loss = model.evaluate(validation)\n        log_metrics(step, train_loss, val_loss)\n`;
const afterCode=beforeCode.replace('    wandb.log({"train/loss": train_loss}, step=step)','    # Keep both curves on the same step axis.\n    metrics = {\n        "train/loss": train_loss,\n        "val/loss": val_loss,\n    }\n    wandb.log(metrics, step=step)');
const specs={
 writing:{project:'Paper studio',task:'Write the paper',agent:'Writing collaborator',path:'~/research/paper-studio',files:{'main.tex':initialTex,'references.bib':'@article{representation2026,\n  title={Representation learning for manipulation},\n  author={Research Team},\n  year={2026}\n}\n','notes.md':'# Paper notes\n\n- Keep the train / validation comparison clear.\n- Avoid claims that exceed the evidence.\n- Add three-seed uncertainty before submission.\n'},activeFile:'main.tex',pages:{Writing:['editor','paper'],Notes:['notes','todos'],Surfboard:['board']},plan:['Draft the method and limitations','Compare training and validation curves','Review the held-out evaluation protocol'],intro:'The source and paper preview are side by side. Select a paragraph to discuss it, or edit the LaTeX and save to update the preview.',prompts:['Review a paragraph','Add a PDF viewer','Show the plan']},
 research:{project:'VLA',task:'Two-arm transfer',agent:'Experiment worker',path:'~/research/vla-simple',files:{'train.py':afterCode,'experiment.yaml':'name: two-arm-transfer\nmethods: [pretrained, from_scratch]\nseeds: [0, 1, 2]\ngpus_per_run: 2\ndataset: two_arm_v1\n','protocol.md':'# Two-arm transfer\n\n## Objective\nCompare sample efficiency with and without pretraining.\n\n## Controls\nSame split, optimizer, GPU allocation, and step budget.\n\n## Reporting\nOverlay training / validation curves between methods.\nEvaluation is separate from the validation split.\n'},activeFile:'experiment.yaml',pages:{Results:['curves','compute'],Protocol:['notes','todos'],Surfboard:['board']},plan:['Compare methods on a fixed protocol','Monitor every 10 minutes or on run failure','Stop monitoring when all runs complete'],intro:'Two methods, one comparison. Solid curves are training; dashed curves are validation. The sample runs and GPU slots are interactive — nothing is submitted to a real machine.',prompts:['Queue a comparison','Add a notes panel','Show the plan']},
 coding:{project:'Training toolkit',task:'Improve metric logging',agent:'Code review worker',path:'~/src/training-toolkit',files:{'train.py':beforeCode,'tests/test_metrics.py':'from train import log_metrics\n\n\ndef test_both_losses_are_logged(monkeypatch):\n    captured = []\n    monkeypatch.setattr("wandb.log",\n                        lambda metrics, step: captured.append(metrics))\n    log_metrics(10, 0.20, 0.28)\n    assert "train/loss" in captured[0]\n    assert "val/loss" in captured[0]\n','README.md':'# Training toolkit\n\nA small example of reviewing agent changes.\n\nThe proposed patch logs both training and validation loss.\nAccept writes it to this browser-local file; Reject keeps your original.\n'},activeFile:'train.py',pages:{Code:['editor','diff'],Tasks:['todos','notes'],Surfboard:['board']},plan:['Inspect the current training logger','Review the proposed agent patch','Keep train and validation on the same step axis'],intro:'The proposed patch adds validation logging without changing the step axis. Review the diff, then Accept or Reject. The editor and files remain available as you move between pages.',prompts:['Explain this diff','Add a file browser','Show the plan']}
};
const panelTypes={editor:['Code editor','Editable source · selection to chat'],paper:['Paper preview','LaTeX source preview · select a paragraph'],curves:['Results','Overlaid training & validation curves'],compute:['Compute & runs','GPU slots and a simulated queue'],diff:['Agent changes','Review a proposed patch · Accept or Reject'],notes:['Notes','Editable Markdown notes'],todos:['To-dos','Checklists saved in this browser'],files:['File browser','Open files without leaving the page'],pdf:['PDF viewer','Multi-page PDF · drop your own file'],board:['Surfboard','The task’s workflow, gates and views']};
const storageKey='supersurfer-workflow-playground-v1';
function fresh(){return {version:1,workflow:'writing',theme:'light',sidebar:true,chat:true,sidebarWidth:213,chatWidth:326,split:50,locked:false,permission:'Approve for me',model:'GPT-6.1 Sol',effort:'High',workflows:Object.fromEntries(Object.entries(specs).map(([id,s])=>[id,{page:Object.keys(s.pages)[0],pages:structuredClone(s.pages),sidePanels:[],files:{...s.files},activeFile:s.activeFile,savedTex:initialTex,notes:s.files['notes.md']||s.files['protocol.md']||'# Implementation notes\n\nThe training logger should publish both losses at each step.\n',todos:s.plan.map(text=>({text,done:false})),messages:[{role:'agent',text:s.intro,created:Date.now()}],agents:[s.agent],agent:s.agent,diff:'pending',runs:[{name:'Pretrained · seed 0',status:'running',gpus:2},{name:'From scratch · seed 0',status:'running',gpus:2}],tick:0,methods:{pretrained:true,scratch:true},metric:'loss',consoleTab:id==='coding'?'terminal':null}]))}}
let state=fresh();try{const saved=JSON.parse(localStorage.getItem(storageKey)||'null');if(saved?.version===1&&saved.workflows)state=saved}catch{}
const requestedWorkflow=new URLSearchParams(location.search).get('workflow');if(Object.hasOwn(specs,requestedWorkflow))state.workflow=requestedWorkflow;
const ws=()=>state.workflows[state.workflow],spec=()=>specs[state.workflow];
const conversation=()=>state.locked?state.workflows[state.lockedWorkflow||state.workflow]:ws();
function persist(){try{localStorage.setItem(storageKey,JSON.stringify(state))}catch{toast('Browser storage is full. Download your files before closing this tab.')}}
let toastTimer;function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3500)}
let monacoPromise,editors=[],contexts=[],arranging=false,renderGeneration=0,pdfUrls=new Map(),tileOrder=[];
const getMonaco=()=>monacoPromise||=import('./vendor/monaco/editor.js').then(m=>{
 m.languages.register({id:'latex'});
 m.languages.setMonarchTokensProvider('latex',{tokenizer:{root:[[/%.*/,'comment'],[/\\[a-zA-Z@]+/,'keyword'],[/[{}]/,'delimiter.bracket'],[/\$[^$]*\$/,'string'],[/[0-9]+/,'number']]}});
 return m;
});
function panelKey(type,index){return `${state.workflow}:${ws().page}:${type}:${index}`}
function render(){
 const generation=++renderGeneration;$$('.tile').forEach(el=>el._pdfTask?.destroy().catch(()=>{}));editors.forEach(e=>{e.editor.dispose();e.models?.forEach(m=>m.dispose())});editors=[];
 document.body.classList.toggle('dark',state.theme==='dark');document.body.classList.toggle('no-sidebar',!state.sidebar);document.body.classList.toggle('no-chat',!state.chat);document.body.classList.toggle('arranging',arranging);
 document.documentElement.style.setProperty('--sidebar',state.sidebarWidth+'px');document.documentElement.style.setProperty('--chat',state.chatWidth+'px');document.documentElement.style.setProperty('--split',state.split+'%');
 $$('[data-workflow]').forEach(b=>{b.classList.toggle('active',b.dataset.workflow===state.workflow);b.setAttribute('aria-current',b.dataset.workflow===state.workflow?'page':'false')});
 $('#show-sidebar').hidden=state.sidebar;$('#project-name').textContent=spec().project;$('#task-name').textContent=spec().task;
 $('#project-nav').innerHTML=Object.entries(specs).map(([id,s])=>`<div class="project-row">${id==='writing'?'▤':id==='research'?'◇':'⌘'} <span>${s.project}</span></div>${id===state.workflow?`<button class="task-row active" data-workflow="${id}"><span class="bullet"></span>${s.task}</button><div class="nav-extra">Task surfboard · ${id}<br>Files and notes stay with this task.</div>`:''}`).join('');
 $('#page-tabs').innerHTML=Object.keys(ws().pages).map(p=>`<button data-page="${escape(p)}" class="${p===ws().page?'active':''}">${escape(p)}</button>`).join('');
 renderFiles();renderChat();$('#arrange').textContent=arranging?'Done arranging':'Arrange';
 const types=ws().pages[ws().page]||[];tileOrder=types.map((type,i)=>({type,key:panelKey(type,i)}));
 $('#panels').innerHTML=types.length?types.map((type,i)=>`${i?'<div class="tile-split" role="separator" aria-label="Resize panels" aria-orientation="vertical" tabindex="0"></div>':''}${tile(type,i,'main')}`).join(''):'<div class="empty-page"><span class="eyebrow">A page for your work</span><h2>What would you like here?</h2><p>Add an editor, PDF viewer, plots, or notes.</p><button class="primary" data-action="add-panel">＋ Add a panel</button></div>';
 $('#sidebar-panels').innerHTML=ws().sidePanels.map((type,i)=>tile(type,i,'sidebar')).join('');
 $$('.tile').forEach(el=>{const key=ws().page+':'+el.dataset.zone+':'+el.dataset.type+':'+el.dataset.index;const height=ws().heights?.[key];if(height){el.style.height=height+'px';el.style.alignSelf='flex-start'}});
 $$('.tile').forEach(el=>mountTile(el,generation));attachResizers();attachDrag();persist();
}
function tile(type,i,zone){const desc=panelTypes[type]||panelTypes.notes;return `<section class="tile" data-type="${type}" data-index="${i}" data-zone="${zone}"><header class="tile-header" ${arranging?'draggable="true"':''}><span class="drag-handle">⠿</span><strong>${desc[0]}</strong><span class="tile-meta">${tileMeta(type)}</span><div class="tile-actions"><button data-action="focus-panel" title="Fullscreen panel" aria-label="Fullscreen ${desc[0]}">⤢</button><button data-action="remove-panel" title="Remove panel" aria-label="Remove ${desc[0]}">×</button></div></header><div class="tile-body" data-content="${type}"></div><div class="tile-footer">${tileFooter(type)}</div><div class="height-handle" role="separator" aria-label="Resize panel height" tabindex="0" title="Drag to change panel height"></div></section>`}
function tileMeta(type){return ({editor:'Monaco editor',paper:'Live source preview',curves:'Illustrative data',compute:'Simulated',diff:'1 file',notes:'Markdown',todos:'.md checklist',pdf:'PDF.js',files:'Task files',board:'Task workflow'})[type]||''}
function tileFooter(type){return ({editor:'<span data-editor-status>Saved in this browser</span><span style="margin-left:auto">⌘ L / Ctrl L · selection to chat</span>',paper:'Demo renderer · not a LaTeX compiler',curves:'Sample curves · not experimental evidence',compute:'No remote connections or actual GPU launches',diff:'Review applies to browser-local files only',notes:'Saved automatically in this browser',todos:'Download as Markdown from the panel',pdf:'Select text, then use Add to chat',files:'Open a file in the current workspace',board:'Each task owns its workflow and views'})[type]||''}
function renderFiles(){const names=[...Object.keys(ws().files),...pdfUrls.keys()].filter((x,i,a)=>a.indexOf(x)===i);$('#file-tree').innerHTML=names.map(name=>`<button class="file ${ws().activeFile===name?'active':''}" data-file="${escape(name)}"><span class="file-icon">${name.endsWith('.tex')?'TᴇX':name.endsWith('.py')?'py':name.endsWith('.pdf')?'PDF':'▤'}</span><span>${escape(name)}</span></button>`).join('')}
function renderChat(){const w=conversation();$('#agent-name').textContent=state.locked?state.lockedName||w.agent:w.agent;$('#lock-agent').classList.toggle('active',state.locked);$('#lock-agent').title=state.locked?'Unlock agent':'Keep this agent while navigating';$('#agent-count').textContent=w.agents.length;$('#agents').innerHTML=w.agents.map(a=>`<button class="agent-row ${a===w.agent?'active':''}" data-agent="${escape(a)}">✧ &nbsp;${escape(a)}</button>`).join('');$('#plan-count').textContent=`${w.todos.filter(t=>t.done).length}/${w.todos.length}`;$('#plan').innerHTML=w.todos.map(t=>`${t.done?'✓':'○'} ${escape(t.text)}`).join('<br>');$('#messages').innerHTML=w.messages.map(messageHTML).join('');$('#chat-suggestions').innerHTML=spec().prompts.map(p=>`<button data-prompt="${escape(p)}">${escape(p)} ↗</button>`).join('');$('#permission').value=state.permission;$('#model').value=state.model;$('#effort').value=state.effort;requestAnimationFrame(()=>{$('#messages').scrollTop=$('#messages').scrollHeight});renderContexts()}
function messageHTML(m){const time=new Date(m.created).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});if(m.role==='check')return `<details class="message check"><summary>✓ ${escape(m.text)}</summary><p>This is a simulated workflow event. No remote jobs or agents were contacted.</p></details>`;return `<div class="message ${m.role}"><div class="who"><b>${m.role==='user'?'You':escape(conversation().agent)}</b><time>${time}</time></div>${escape(m.text).split('\n\n').map(p=>`<p>${p.replaceAll('\n','<br>')}</p>`).join('')}${m.context?.length?`<span class="pill">${m.context.length} attached selection${m.context.length>1?'s':''}</span>`:''}</div>`}
function addMessage(role,text,context=[]){conversation().messages.push({role,text,context,created:Date.now()});renderChat();persist()}
function renderContexts(){$('#context-chips').innerHTML=contexts.map((c,i)=>`<div class="context-chip" title="${escape(c.text)}"><span>▤ ${escape(c.label)}</span><button type="button" data-context-remove="${i}" aria-label="Remove context">×</button></div>`).join('')}
function attachContext(label,text){if(!text.trim()){toast('Select some text first.');return}contexts.push({label,text:text.slice(0,16000)});renderContexts();if(!state.chat){state.chat=true;render()}document.body.classList.add('show-mobile-chat');$('#message').focus();toast('Selection attached. Add your message and send.');persist()}
function editorMarkup(){return `<div class="editor-tools"><button data-action="editor-files">Files</button><button data-action="terminal">Terminal</button><button data-action="ports">Ports</button><button data-action="show-diff">Agent changes</button><span class="spacer"></span><button data-action="font-minus" title="Smaller text">A−</button><button data-action="font-plus" title="Larger text">A＋</button><button data-action="ask-selection">Add to chat</button><button class="primary" data-action="save-file">Save</button></div><div class="code-location">${escape(spec().path)}/${escape(ws().activeFile)}</div><div class="file-tab">${escape(ws().activeFile)}<span class="dirty-dot"></span><span class="pill">${language(ws().activeFile)}</span><button data-action="copy-path" title="Copy full path">⧉</button></div><div class="monaco-host"></div>`}
function language(name){return name.endsWith('.tex')?'latex':name.endsWith('.py')?'python':name.endsWith('.md')?'markdown':name.endsWith('.json')?'json':name.endsWith('.yaml')?'yaml':'plaintext'}
async function mountTile(el,generation){const type=el.dataset.type,body=$('.tile-body',el);try{
 if(type==='editor'){body.classList.add('editor-body');body.innerHTML=editorMarkup();el._console=mountEditorConsole(el,{state:ws(),files:ws().files,path:spec().path,persist,dialog:modal});const m=await getMonaco();if(!el.isConnected||generation!==renderGeneration)return;const wf=state.workflow,file=ws().activeFile,model=m.editor.createModel(ws().files[file]||'',language(file));const editor=m.editor.create($('.monaco-host',el),{model,theme:state.theme==='dark'?'vs-dark':'vs',automaticLayout:true,fontSize:ws().fontSize||13,fontFamily:'"SFMono-Regular",Consolas,"Liberation Mono",monospace',minimap:{enabled:false},wordWrap:'on',scrollBeyondLastLine:false,padding:{top:14,bottom:15},renderLineHighlight:'none',lineNumbersMinChars:3,folding:true,tabSize:4});editors.push({el,editor,models:[model],file,wf});editor.onDidChangeModelContent(()=>{state.workflows[wf].files[file]=editor.getValue();el.classList.add('dirty');$('[data-editor-status]',el).textContent='Unsaved preview · source kept in browser';persist()});editor.addCommand(m.KeyMod.CtrlCmd|m.KeyCode.KeyL,()=>attachEditorSelection(el));editor.addCommand(m.KeyMod.CtrlCmd|m.KeyCode.KeyS,()=>saveFile(el));return}
 if(type==='paper'){body.innerHTML=paperHTML();return}
 if(type==='curves'){body.innerHTML=curvesHTML();drawChart(body);return}
 if(type==='compute'){body.innerHTML=computeHTML();return}
 if(type==='diff'){body.classList.add('editor-body');body.innerHTML=`<div class="diff-summary"><b>train.py</b><span class="plus">+6</span><span class="minus">−1</span><button class="primary" data-action="accept-diff" ${ws().diff!=='pending'?'disabled':''}>Accept</button><button class="outline" data-action="reject-diff" ${ws().diff!=='pending'?'disabled':''}>Reject</button></div><div class="diff-status">${ws().diff==='pending'?'Proposed by the code review worker · not applied':ws().diff==='accepted'?'✓ Accepted · train.py updated in this browser':'Rejected · original file preserved'} ${ws().diff!=='pending'?'<button data-action="reset-diff">Review again</button>':''}</div><div class="monaco-host"></div>`;const m=await getMonaco();if(!el.isConnected||generation!==renderGeneration)return;const original=m.editor.createModel(beforeCode,'python'),modified=m.editor.createModel(afterCode,'python');const editor=m.editor.createDiffEditor($('.monaco-host',el),{theme:state.theme==='dark'?'vs-dark':'vs',automaticLayout:true,renderSideBySide:false,readOnly:true,originalEditable:false,fontSize:12,minimap:{enabled:false},scrollBeyondLastLine:false,wordWrap:'on',hideUnchangedRegions:{enabled:false},padding:{top:10}});editor.setModel({original,modified});editors.push({el,editor,models:[original,modified]});return}
 if(type==='notes'){body.innerHTML=`<textarea class="note-editor" aria-label="Markdown notes">${escape(ws().notes)}</textarea>`;$('.note-editor',body).addEventListener('input',e=>{ws().notes=e.target.value;persist()});return}
 if(type==='todos'){body.innerHTML=`<div class="todo-list">${ws().todos.map((t,i)=>`<label><input type="checkbox" data-todo="${i}" ${t.done?'checked':''}><span>${escape(t.text)}</span></label>`).join('')}<form class="todo-add"><input aria-label="New to-do" placeholder="Add a to-do…" required maxlength="300"><button class="outline">Add</button></form><button class="quiet" data-action="download-todos">↓ Download .md</button></div>`;$('.todo-add',body).addEventListener('submit',e=>{e.preventDefault();ws().todos.push({text:$('input',e.target).value,done:false});render()});return}
 if(type==='files'){body.innerHTML=`<div style="padding:12px">${Object.keys(ws().files).map(name=>`<button class="file" data-file="${escape(name)}"><span class="file-icon">▤</span><span>${escape(name)}</span></button>`).join('')}<button class="outline" data-action="upload" style="margin:12px 5px">＋ Import from your computer</button></div>`;return}
 if(type==='pdf'){body.classList.add('editor-body');const file=ws().pdfFile||'sample-paper.pdf';body.innerHTML=`<div class="pdf-toolbar"><span>${escape(file)}</span><button data-action="pdf-selection">Add to chat</button><button data-action="upload">Open PDF…</button><select data-pdf-scale aria-label="PDF zoom"><option value="1">Fit width</option><option value="1.25">125%</option><option value="1.5">150%</option></select></div><div class="pdf-pages"><div class="panel-error">Loading all pages…</div></div>`;await renderPDF(el,file,1,generation);return}
 if(type==='board'){body.innerHTML=boardHTML();return}
}catch(error){if(!el.isConnected||generation!==renderGeneration)return;body.innerHTML=`<div class="panel-error">This panel could not load.<br>${escape(error.message)}<br><button data-action="retry-panel">Try again</button></div>`;console.error(error)}}
function paperHTML(){const tex=ws().savedTex||initialTex;const get=(pattern,fallback)=>tex.match(pattern)?.[1]||fallback;const clean=s=>escape(s.replace(/%[^\n]*/g,'').replace(/\\(emph|textbf|textit)\{([^}]*)\}/g,'$2').replace(/\\cite\{[^}]*\}/g,'[reference]').replace(/\\[a-zA-Z]+(?:\[[^\]]*\])?(?:\{[^}]*\})?/g,'').replace(/[{}]/g,'').replace(/\s+/g,' ').trim());const title=clean(get(/\\title\{([^}]*)\}/,'Your paper'));const abstract=clean(get(/\\begin\{abstract\}([\s\S]*?)\\end\{abstract\}/,'Add an abstract to your source.'));const sections=[...tex.matchAll(/\\section\{([^}]*)\}([\s\S]*?)(?=\\section\{|\\end\{document\}|$)/g)].map((m,i)=>`<h2>${i+1}. ${clean(m[1])}</h2><p>${clean(m[2])}</p>${i===1?`${miniChart()}<div class="paper-caption">Illustrative training and validation loss. Solid: train; dashed: validation.</div>`:''}`).join('');return `<div class="editor-tools"><span class="pill">Updates on Save</span><span class="spacer"></span><button data-action="paper-selection">Add selection to chat</button><button data-action="download-source">↓ Source</button></div><div class="paper-scroll"><article class="paper"><div class="paper-kicker">RESEARCH PAPER · INTERACTIVE EXAMPLE</div><h1>${title}</h1><div class="authors">Research team · Draft for discussion</div><h2 style="text-align:center">Abstract</h2><p>${abstract}</p>${sections||'<p>Add a section to begin writing.</p>'}<hr style="border:0;border-top:1px solid #dce1e5;margin:27px 0"><p class="paper-caption">This page is a simplified preview of your source, not a compiled PDF. Open a PDF panel to view an actual PDF.</p></article></div>`}
const chartData=Array.from({length:41},(_,i)=>{const step=i*500;return {step,pretrainedTrain:.62*Math.exp(-i/9)+.12+.006*Math.sin(i*2),pretrainedVal:.55*Math.exp(-i/10)+.19+.008*Math.sin(i*1.6),scratchTrain:.72*Math.exp(-i/15)+.18+.009*Math.sin(i*1.7),scratchVal:.66*Math.exp(-i/15)+.28+.01*Math.sin(i*1.4)}});
function miniChart(){const line=(key)=>chartData.map((p,i)=>`${i?'L':'M'}${(35+i*8).toFixed(1)},${(140-p[key]*115).toFixed(1)}`).join('');return `<svg viewBox="0 0 380 175" class="mini-curves" aria-label="Illustrative overlaid training and validation losses"><path d="M35 20V140H365" fill="none" stroke="#b4c1ca"/><text x="10" y="20" fill="#83929d" font-size="8">Loss</text><text x="330" y="160" fill="#83929d" font-size="8">Steps</text>${['pretrainedTrain','pretrainedVal','scratchTrain','scratchVal'].map((k,i)=>`<path d="${line(k)}" fill="none" stroke="${i<2?'#348977':'#5986ba'}" stroke-width="1.8" ${i%2?'stroke-dasharray="5 3"':''}/>`).join('')}</svg>`}
function curvesHTML(){return `<div class="results"><div class="results-top"><div><span class="eyebrow">E14 · Two-arm transfer</span><h2>Does pretraining help?</h2><p>Same data split, same budget. Compare both methods<br>before drawing conclusions.</p></div><span class="status">${ws().runs.filter(r=>r.status==='running').length} running</span></div><div class="stat-row"><div class="stat"><span class="label">Pretrained · val loss</span><b>0.20</b><small>Illustrative</small></div><div class="stat"><span class="label">From scratch · val loss</span><b>0.33</b><small>Illustrative</small></div><div class="stat"><span class="label">Step</span><b>20k</b><small>Sample checkpoint</small></div></div><div class="chart-toolbar"><strong>Learning curves</strong><select data-chart-metric aria-label="Chart metric"><option value="loss" ${ws().metric==='loss'?'selected':''}>Loss ↓</option><option value="accuracy" ${ws().metric==='accuracy'?'selected':''}>Success rate ↑</option></select></div><div class="legend"><label><input type="checkbox" data-method="pretrained" ${ws().methods.pretrained?'checked':''}><span class="legend-line"></span>Pretrained</label><label><input type="checkbox" data-method="scratch" ${ws().methods.scratch?'checked':''}><span class="legend-line blue"></span>From scratch</label></div><div class="split-legend">━ Training &nbsp;&nbsp; ┄ Validation · all methods on the same axes</div><div class="chart-wrap"><svg class="chart" viewBox="0 0 600 300" role="img" aria-label="Training and validation curves overlaid between methods"></svg><div class="chart-tooltip" hidden></div></div><div class="chart-note">Hover to inspect · 0–20,000 steps · no smoothing</div><table class="comparison-table"><thead><tr><th>Method</th><th>Train</th><th>Validation</th><th>GPU hours</th></tr></thead><tbody><tr><td>Pretrained</td><td>0.13</td><td>0.20</td><td>1.8</td></tr><tr><td>From scratch</td><td>0.23</td><td>0.33</td><td>1.8</td></tr></tbody></table><div class="results-link">W&amp;B → results view · In the connected app, curves load from your actual runs.<br>This demo uses synthetic sample values.</div></div>`}
function drawChart(body){const svg=$('.chart',body);if(!svg)return;const metric=ws().metric,x=i=>48+i*13.05,y=v=>254-v*224;let content='';for(let i=0;i<=5;i++){const v=i/5;content+=`<line class="grid" x1="48" x2="570" y1="${y(v)}" y2="${y(v)}"/><text x="37" y="${y(v)+3}" text-anchor="end">${metric==='loss'?v.toFixed(1):Math.round(v*100)+'%'}</text>`}for(let i=0;i<=4;i++){content+=`<text x="${48+i*130.5}" y="277" text-anchor="middle">${i*5}k</text>`}content+=`<text x="309" y="298" text-anchor="middle">Training step</text><text x="50" y="14">${metric==='loss'?'Loss ↓':'Success rate ↑'}</text>`;for(const method of ['pretrained','scratch']){if(!ws().methods[method])continue;for(const split of ['Train','Val']){const path=chartData.map((p,i)=>`${i?'L':'M'}${x(i).toFixed(1)},${y(metric==='loss'?p[method+split]:Math.max(0,1-p[method+split])).toFixed(1)}`).join('');content+=`<path data-curve="${method+split}" d="${path}" stroke="${method==='pretrained'?'#348977':'#5986ba'}" stroke-width="2.2" fill="none" ${split==='Val'?'stroke-dasharray="6 4"':''}/>`}}content+='<line class="hover-line" y1="28" y2="254" stroke="#90a5b6" stroke-dasharray="3 4" visibility="hidden"/>';svg.innerHTML=content;svg.onpointermove=e=>{const rect=svg.getBoundingClientRect(),plotX=(e.clientX-rect.left)/rect.width*600,index=Math.max(0,Math.min(40,Math.round((plotX-48)/13.05))),p=chartData[index],tip=$('.chart-tooltip',body);tip.hidden=false;tip.style.left=Math.min(rect.width-155,Math.max(0,e.clientX-rect.left-65))+'px';tip.style.top='30px';const val=k=>metric==='loss'?p[k].toFixed(3):((1-p[k])*100).toFixed(1)+'%';tip.innerHTML=`<b>Step ${p.step.toLocaleString()}</b><br>${ws().methods.pretrained?`Pretrained: ${val('pretrainedTrain')} / ${val('pretrainedVal')}<br>`:''}${ws().methods.scratch?`Scratch: ${val('scratchTrain')} / ${val('scratchVal')}<br>`:''}<span style="color:var(--muted)">Train / validation</span>`;const hover=$('.hover-line',svg);hover.setAttribute('x1',x(index));hover.setAttribute('x2',x(index));hover.setAttribute('visibility','visible')};svg.onpointerleave=()=>{$('.chart-tooltip',body).hidden=true;$('.hover-line',svg).setAttribute('visibility','hidden')}}
function computeHTML(){const occupied=ws().runs.filter(r=>r.status==='running').reduce((n,r)=>n+r.gpus,0);let busy=Math.min(occupied,ws().gearheadReady?20:16);return `<div class="node-list">${['Tulip','Trinity · 3-8','Gearhead'].map((name,i)=>{const count=i===2?4:8;const slots=Array.from({length:count},(_,j)=>{const used=busy>0;if(used)busy--;return `<div class="gpu ${used?'busy':i===2&&!ws().gearheadReady?'reserved':''}" title="GPU ${j} · ${used?'Running':'Available'} · ${i===2?'24':'80'} GB">${j}</div>`}).join('');return `<div class="node"><div class="node-head"><b>${name}</b><span>${count} × ${i===2?'RTX 4090 · '+(ws().gearheadReady?'ready':'needs dataset'):'A100 · ready'}</span></div><div class="gpu-bars">${slots}</div></div>`}).join('')}</div><div class="gpu-legend"><span><i></i>Available</span><span><i class="busy"></i>Running</span><span><i style="background:#e7c887"></i>Needs setup</span><button data-action="refresh-gpus" title="Refresh GPU availability now">↻ Refresh</button></div>${ws().gearheadReady?'':'<div style="padding:0 14px 14px"><button class="outline" data-action="prepare-node" style="font-size:10px;width:100%">Prepare Gearhead · demo</button></div>'}<div class="runs"><h3>Runs <span class="pill">${ws().runs.length}</span></h3>${ws().runs.map((r,i)=>`<div class="run"><div class="run-name"><b>${escape(r.name)}</b><span class="status ${r.status==='queued'?'queued':''}">${r.status}</span></div><div class="run-meta"><span>${r.gpus} GPUs</span><span>${r.status==='running'?'Started '+(i<2?'26 minutes ago':'just now'):r.status==='queued'?'Waiting for capacity':'Completed in this demo'}</span></div></div>`).join('')}<button class="run-queue outline" data-action="queue-run">＋ Queue a sample run</button><div class="queue-info">Tulip and Trinity are prepared. Gearhead needs data.<br>When ready-node capacity is full, new runs wait. Try adding several.</div></div>`}
function boardHTML(){const steps=state.workflow==='writing'?['Draft LaTeX','Save source','Preview paper','Review with agent']:state.workflow==='research'?['Experiment protocol','Reviewed commit','GPU queue','W&B metrics','Results view']:['Assign coding task','Agent proposes patch','Review diff','Accept or Reject','Validate change'];return `<div class="readme"><span class="eyebrow">${state.workflow} surfboard · task level</span><h2>A small workflow with clear steps.</h2><p>This task owns its workflow. A project can contain writing, research and coding tasks.</p><div style="display:flex;flex-wrap:wrap;gap:8px;margin:25px 0">${steps.map((s,i)=>`${i?'<span style="padding-top:12px;color:var(--muted)">→</span>':''}<span style="border:1px solid var(--line);border-radius:9px;background:var(--solid);padding:12px 14px;font-size:11px">${s}</span>`).join('')}</div><h3 style="font-size:12px">While you’re away</h3><p>${state.workflow==='research'?'The connected worker can monitor every 10 minutes and wake on run failures. Monitoring stops when the assigned runs complete. No monitoring happens in this demo.':'The connected agent follows the assigned deliverables. Review gates stay visible; changes and messages retain their task context. There are no live agents in this demo.'}</p><h3 style="font-size:12px">Views are yours</h3><p>Add pages, move panels into the sidebar, resize dividers, or put a panel fullscreen. Each workflow remembers its layout in this browser.</p><button class="outline" data-action="add-panel">＋ Add a view block</button></div>`}
async function renderPDF(el,file,scale=1,generation=renderGeneration){const epoch=(el._pdfEpoch||0)+1;el._pdfEpoch=epoch;await el._pdfTask?.destroy();const container=$('.pdf-pages',el),target=pdfUrls.get(file)||'./sample-paper.pdf';const pdfjs=await import('./vendor/pdfjs/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc=new URL('./vendor/pdfjs/pdf.worker.mjs',import.meta.url).href;const task=pdfjs.getDocument({url:new URL(target,import.meta.url).href,cMapUrl:new URL('./vendor/pdfjs/cmaps/',import.meta.url).href,standardFontDataUrl:new URL('./vendor/pdfjs/standard_fonts/',import.meta.url).href,wasmUrl:new URL('./vendor/pdfjs/wasm/',import.meta.url).href});el._pdfTask=task;const pdf=await task.promise;if(!el.isConnected||generation!==renderGeneration||epoch!==el._pdfEpoch){await task.destroy();return}container.innerHTML='';const width=Math.max(180,container.clientWidth-32);for(let n=1;n<=pdf.numPages;n++){if(!el.isConnected||epoch!==el._pdfEpoch)break;const page=await pdf.getPage(n),base=page.getViewport({scale:1}),viewport=page.getViewport({scale:width/base.width*scale});const wrapper=document.createElement('div');wrapper.className='pdf-page';wrapper.style.width=viewport.width+'px';wrapper.style.height=viewport.height+'px';wrapper.style.setProperty('--total-scale-factor',viewport.scale);const canvas=document.createElement('canvas');const pixelRatio=window.devicePixelRatio||1;canvas.width=Math.floor(viewport.width*pixelRatio);canvas.height=Math.floor(viewport.height*pixelRatio);canvas.style.width=viewport.width+'px';canvas.style.height=viewport.height+'px';wrapper.append(canvas);container.append(wrapper);await page.render({canvasContext:canvas.getContext('2d'),viewport,transform:pixelRatio!==1?[pixelRatio,0,0,pixelRatio,0,0]:null}).promise;const text=document.createElement('div');text.className='textLayer';wrapper.append(text);const content=await page.getTextContent();await new pdfjs.TextLayer({textContentSource:content,container:text,viewport}).render()}if(!el.isConnected||epoch!==el._pdfEpoch)return;$('.tile-meta',el).textContent=`${pdf.numPages} pages · PDF.js`}
function attachEditorSelection(el){const ref=editors.find(e=>e.el===el);if(!ref?.file)return;const selection=ref.editor.getSelection(),text=ref.editor.getModel().getValueInRange(selection);attachContext(`${ref.file}:${selection.startLineNumber}–${selection.endLineNumber}`,text)}
function saveFile(el){const ref=editors.find(e=>e.el===el);if(!ref?.file)return;if(ref.file.endsWith('.tex')){ws().savedTex=ref.editor.getValue();$$('[data-content="paper"]').forEach(b=>b.innerHTML=paperHTML())}el.classList.remove('dirty');$('[data-editor-status]',el).textContent='Saved in this browser';persist();toast(ref.file.endsWith('.tex')?'Saved · paper preview updated.':'Saved in this browser.')}
function openFile(name){if(pdfUrls.has(name)){ws().pdfFile=name;ensurePanel('pdf');return}ws().activeFile=name;if(!ws().pages[ws().page].includes('editor')&&!ws().sidePanels.includes('editor'))ws().pages[ws().page].unshift('editor');render();toast('Opened in this page. Your other panels stay in place.')}
function ensurePanel(type){if(!ws().pages[ws().page].includes(type)&&!ws().sidePanels.includes(type))ws().pages[ws().page].push(type);render()}
function modal(title,html){$('#dialog-content').innerHTML=`<div class="dialog-top"><h2>${title}</h2><button data-action="close-dialog" aria-label="Close dialog">×</button></div>${html}`;$('#dialog').showModal()}
function showPanelPicker(){modal('Make room for your work.',`<p>Add a building block to this task’s current page. Use Arrange to move it to a sidebar.</p><div class="dialog-grid">${Object.entries(panelTypes).map(([type,[name,desc]])=>`<button data-add-type="${type}"><b>${name}</b><span>${desc}</span></button>`).join('')}</div>`)}
function showTour(){const descriptions={writing:[['Edit the source','Change a sentence in main.tex, then Save. The paper preview updates.'],['Bring a selection to chat','Highlight source and press ⌘ L / Ctrl L, or select a paragraph in the preview and use Add selection to chat.'],['Make the layout yours','Drag the divider, use ⤢ on any panel, or Arrange and drop a panel into the sidebar.']],research:[['Compare methods','Toggle the method legends and hover on the overlaid training / validation curves.'],['Try the queue','Add sample runs. Prepared nodes fill first; excess work waits in the queue. Refresh updates the simulation.'],['Add your own view','Add a page or panel, then move it to the sidebar in Arrange mode.']],coding:[['Review agent changes','Accept writes the proposed patch to the local editor. Reject preserves your original.'],['Work with files','Open files from the tree without leaving this page. Select source and attach it to the conversation.'],['Keep the editor roomy','Resize the divider, close chat, or put the editor fullscreen.']]};modal('Try the '+state.workflow+' workflow.',`<p>This is a browser-local interactive prototype of SuperSurfer. All agents, metrics and runs are sample data.</p>${descriptions[state.workflow].map(([title,desc],i)=>`<div class="tour-step"><span>${i+1}</span><div><b>${title}</b><p>${desc}</p></div></div>`).join('')}<div class="tour-footer"><span>Edits and layouts stay in this browser.</span><button class="primary" data-action="close-dialog">Start exploring →</button></div>`)}
function download(name,text,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function queueRun(){const count=ws().runs.filter(r=>r.status==='running').reduce((n,r)=>n+r.gpus,0),run={name:'Comparison · seed '+Math.max(1,ws().runs.length-1),status:count+2<=(ws().gearheadReady?20:16)?'running':'queued',gpus:2};ws().runs.push(run);render();toast(run.status==='running'?'Sample run assigned to a prepared node.':'Sample run queued · no free slots on eligible nodes.');return run}
async function sendMessage(text){text=text.trim();if(!text)return;const attached=contexts;contexts=[];$('#message').value='';$('#message').style.height='auto';addMessage('user',text,attached);const lower=text.toLowerCase();let reply;
 if(/add.*pdf/.test(lower)){ensurePanel('pdf');reply='Added a PDF viewer to this page. Drop a PDF from your computer into it, or use Open PDF to explore the sample.'}
 else if(/add.*(file browser|file explorer)/.test(lower)){ensurePanel('files');reply='Added a file browser. Opening a file keeps the current page and surrounding panels in place.'}
 else if(/add.*(note|markdown)/.test(lower)){ensurePanel('notes');reply='Added a Markdown notes panel. Changes are saved in this browser.'}
 else if(/add.*(page|view)/.test(lower)){const name='Agent page '+(Object.keys(ws().pages).length-2);ws().pages[name]=['notes'];ws().page=name;render();reply='Added a new page with notes. You can add more panels or move them using Arrange.'}
 else if(/queue/.test(lower)&&state.workflow==='research'){const run=queueRun();reply=`Created a sample comparison run with two GPUs. Its status is ${run.status}. This is a simulation; no real job was submitted.`}
 else if(/(plan|deliverable)/.test(lower)){reply='The plan is:\n'+ws().todos.map((t,i)=>`${i+1}. ${t.text}${t.done?' ✓':''}`).join('\n')+'\n\nIn the connected app, the agent keeps pursuing unfinished deliverables. This demo does not run background work.';$('.deliverables').open=true}
 else if(state.workflow==='coding'&&/diff|explain/.test(lower)){reply='The original logger drops validation loss. The proposed patch adds val/loss and sends both metrics in the same call, preserving the training step.\n\nAccept applies this exact patch to the browser-local file. Reject keeps the current file.'}
 else if(state.workflow==='writing'&&(attached.length||/review|paragraph/.test(lower))){reply=attached.length?'Demo review: keep the claim tied to the observed comparison, state the shared training budget, and separate validation findings from held-out evaluation.\n\nThe selected text is attached to your message; your source has not been changed.':'Select a paragraph in the paper preview, then click Add selection to chat. Or select LaTeX source and press ⌘ L / Ctrl L. Your selection appears as a compact attachment rather than a pasted block.'}
 else reply='Your message is saved in this demo conversation. Try “add a PDF viewer”, “add a notes panel”, or “show the plan” to see the interactive workflow.\n\nThis prototype uses scripted replies; the installed app connects to your actual agents.';
 addMessage('check','Demo action processed');addMessage('agent',reply)
}
document.addEventListener('click',async e=>{const workflow=e.target.closest('[data-workflow]');if(workflow){state.workflow=workflow.dataset.workflow;contexts=[];document.body.classList.remove('show-mobile-chat');render();return}const page=e.target.closest('[data-page]');if(page){ws().page=page.dataset.page;render();return}const file=e.target.closest('[data-file]');if(file){openFile(file.dataset.file);return}const agent=e.target.closest('[data-agent]');if(agent){ws().agent=agent.dataset.agent;renderChat();persist();return}const add=e.target.closest('[data-add-type]');if(add){$('#dialog').close();ensurePanel(add.dataset.addType);return}const prompt=e.target.closest('[data-prompt]');if(prompt){sendMessage(prompt.dataset.prompt);return}const remove=e.target.closest('[data-context-remove]');if(remove){contexts.splice(Number(remove.dataset.contextRemove),1);renderContexts();return}
 const button=e.target.closest('[data-action]');if(!button)return;const action=button.dataset.action,el=button.closest('.tile');
 if(action==='home'||action==='tour'){showTour();return}
 if(action==='close-dialog'){$('#dialog').close();return}
 if(action==='theme'){state.theme=state.theme==='dark'?'light':'dark';render();return}
 if(action==='reset'){modal('Reset this demo?',`<p>This clears your browser-local edits, conversations, uploads and layouts. Your actual workspace is unaffected.</p><button class="primary" data-action="confirm-reset">Restore sample workspace</button>`);return}
 if(action==='confirm-reset'){pdfUrls.forEach(URL.revokeObjectURL);pdfUrls.clear();state=fresh();contexts=[];arranging=false;$('#dialog').close();render();toast('Sample workspace restored.');return}
 if(action==='sidebar'){if(innerWidth<930){document.body.classList.toggle('mobile-sidebar')}else{state.sidebar=!state.sidebar;render()}return}
 if(action==='chat'){if(innerWidth<=680){document.body.classList.toggle('show-mobile-chat')}else{state.chat=!state.chat;render()}return}
 if(action==='chat-focus'){$('#chat').classList.toggle('fullscreen');return}
 if(action==='lock'){state.locked=!state.locked;state.lockedName=ws().agent;state.lockedWorkflow=state.workflow;renderChat();persist();toast(state.locked?'Agent stays with you while you navigate.':'Agent follows the current task.');return}
 if(action==='new-agent'){modal('New task agent',`<p>Name a sample agent for this task.</p><form id="new-agent-form"><input class="dialog-input" name="name" placeholder="Agent name" maxlength="60" required><button class="primary">Create agent</button></form>`);$('#new-agent-form').onsubmit=e=>{e.preventDefault();const name=new FormData(e.target).get('name').trim();if(!name)return;ws().agents.push(name);ws().agent=name;$('#dialog').close();render()};return}
 if(action==='add-page'){modal('Add a task page',`<p>A page is a place for panels. Your existing files and conversation stay available.</p><form id="add-page-form"><input class="dialog-input" name="name" placeholder="Page name" maxlength="40" required><button class="primary">Create page</button></form>`);$('#add-page-form').onsubmit=e=>{e.preventDefault();const name=new FormData(e.target).get('name').trim();if(!name)return;if(Object.hasOwn(ws().pages,name)){toast('A page with this name already exists.');return}ws().pages[name]=[];ws().page=name;$('#dialog').close();render()};return}
 if(action==='add-panel'){showPanelPicker();return}
 if(action==='arrange'){arranging=!arranging;render();if(arranging)toast('Drag a panel header to the sidebar or another panel. Resize with the dividers.');return}
 if(action==='remove-panel'){const list=el.dataset.zone==='sidebar'?ws().sidePanels:ws().pages[ws().page];list.splice(Number(el.dataset.index),1);render();return}
 if(action==='focus-panel'){el.classList.toggle('fullscreen');button.title=el.classList.contains('fullscreen')?'Exit fullscreen':'Fullscreen panel';editors.forEach(e=>e.editor.layout());return}
 if(action==='terminal'||action==='ports'){el._console?.show(action);return}
 if(action==='ask-selection'){attachEditorSelection(el);return}
 if(action==='save-file'){saveFile(el);return}
 if(action==='font-plus'||action==='font-minus'){ws().fontSize=Math.max(9,Math.min(28,(ws().fontSize||13)+(action==='font-plus'?1:-1)));editors.filter(e=>e.file).forEach(e=>e.editor.updateOptions({fontSize:ws().fontSize}));persist();return}
 if(action==='copy-path'){try{await navigator.clipboard.writeText(spec().path+'/'+ws().activeFile);toast('Path copied.')}catch{toast(spec().path+'/'+ws().activeFile)}return}
 if(action==='show-diff'){ensurePanel('diff');return}
 if(action==='editor-files'){ensurePanel('files');return}
 if(action==='paper-selection'||action==='pdf-selection'){const text=window.getSelection()?.toString()||'';attachContext(action==='paper-selection'?'Paper paragraph':ws().pdfFile||'PDF selection',text);return}
 if(action==='accept-diff'||action==='reject-diff'){if(ws().diff!=='pending')return;if(action==='accept-diff'&&ws().files['train.py']!==beforeCode){toast('train.py has changed. Keep your edits or restore the sample before applying this patch.');return}ws().diff=action==='accept-diff'?'accepted':'rejected';if(ws().diff==='accepted')ws().files['train.py']=afterCode;render();addMessage('check',ws().diff==='accepted'?'Accepted agent patch · train.py updated':'Rejected agent patch · current file preserved');toast(ws().diff==='accepted'?'Accepted · local file updated.':'Rejected · file unchanged.');return}
 if(action==='reset-diff'){ws().diff='pending';render();return}
 if(action==='download-source'){download('main.tex',ws().files['main.tex']||initialTex);return}
 if(action==='download-todos'){download('todos.md','# To-dos\n\n'+ws().todos.map(t=>`- [${t.done?'x':' '}] ${t.text}`).join('\n')+'\n','text/markdown');return}
 if(action==='queue-run'){queueRun();return}
 if(action==='prepare-node'){ws().gearheadReady=true;let occupied=ws().runs.filter(r=>r.status==='running').reduce((n,r)=>n+r.gpus,0);ws().runs.filter(r=>r.status==='queued').forEach(r=>{if(occupied+r.gpus<=20){r.status='running';occupied+=r.gpus}});render();addMessage('check','Demo onboarding: environment, data and commit checked · Gearhead eligible');toast('Gearhead prepared in this simulation. Queued work can use its four GPUs.');return}
 if(action==='refresh-gpus'){ws().tick++;const run=ws().runs.find(r=>r.status==='running');if(run&&ws().tick>1)run.status='completed';let occupied=ws().runs.filter(r=>r.status==='running').reduce((n,r)=>n+r.gpus,0);ws().runs.filter(r=>r.status==='queued').forEach(r=>{if(occupied+r.gpus<=(ws().gearheadReady?20:16)){r.status='running';occupied+=r.gpus}});render();toast('Sample GPU observation refreshed'+(ws().tick>1?' · queue advanced.':'.'));return}
 if(action==='upload'){$('#file-input').click();return}
 if(action==='retry-panel'){mountTile(el,renderGeneration);return}
});
document.addEventListener('change',e=>{if(e.target.matches('[data-method]')){ws().methods[e.target.dataset.method]=e.target.checked;drawChart(e.target.closest('.tile-body'));persist()}if(e.target.matches('[data-chart-metric]')){ws().metric=e.target.value;drawChart(e.target.closest('.tile-body'));persist()}if(e.target.matches('[data-todo]')){ws().todos[Number(e.target.dataset.todo)].done=e.target.checked;renderChat();persist()}if(e.target.matches('[data-pdf-scale]'))renderPDF(e.target.closest('.tile'),ws().pdfFile||'sample-paper.pdf',Number(e.target.value));if(['permission','model','effort'].includes(e.target.id)){state[e.target.id]=e.target.value;persist()}});
$('#composer').addEventListener('submit',e=>{e.preventDefault();sendMessage($('#message').value)});$('#message').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();sendMessage(e.target.value)}});$('#message').addEventListener('input',e=>{e.target.style.height='auto';e.target.style.height=Math.min(110,e.target.scrollHeight)+'px'});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$$('.fullscreen').forEach(p=>p.classList.remove('fullscreen'));document.body.classList.remove('mobile-sidebar');editors.forEach(e=>e.editor.layout())}});
function attachResizers(){const bind=(node,get,set,min,max)=>{if(!node)return;node.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();const start=e.clientX,initial=get();document.body.classList.add('resizing');node.setPointerCapture(e.pointerId);node.onpointermove=ev=>set(Math.min(max(),Math.max(min(),initial+ev.clientX-start)));node.onpointerup=()=>{document.body.classList.remove('resizing');node.onpointermove=null;persist()}};node.onkeydown=e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();set(Math.min(max(),Math.max(min(),get()+(e.key==='ArrowLeft'?-12:12))));persist()}};
 bind($('.sidebar-split'),()=>state.sidebarWidth,v=>{state.sidebarWidth=v;document.documentElement.style.setProperty('--sidebar',v+'px')},()=>140,()=>340);
 bind($('.chat-split'),()=>-state.chatWidth,v=>{state.chatWidth=-v;document.documentElement.style.setProperty('--chat',(-v)+'px')},()=>-Math.min(700,innerWidth*.55),()=>-240);
 $$('.tile-split').forEach((node,i)=>{const left=node.previousElementSibling,right=node.nextElementSibling,parent=node.parentElement;bind(node,()=>left.getBoundingClientRect().width,v=>{left.style.flex=`0 0 ${v}px`;right.style.flex='1';state.split=v/(parent.clientWidth-9)*100},()=>180,()=>parent.clientWidth-190)});
 $$('.height-handle').forEach(node=>{node.onpointerdown=e=>{e.preventDefault();const el=node.closest('.tile'),start=e.clientY,height=el.offsetHeight;node.setPointerCapture(e.pointerId);node.onpointermove=ev=>{el.style.height=Math.max(240,height+ev.clientY-start)+'px';el.style.alignSelf='flex-start';el.style.flexShrink='0';editors.filter(x=>x.el===el).forEach(x=>x.editor.layout())};node.onpointerup=()=>{node.onpointermove=null;ws().heights||={};ws().heights[ws().page+':'+el.dataset.zone+':'+el.dataset.type+':'+el.dataset.index]=el.offsetHeight;persist()}};node.onkeydown=e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();const el=node.closest('.tile');el.style.height=Math.max(240,el.offsetHeight+(e.key==='ArrowUp'?-30:30))+'px';el.style.alignSelf='flex-start';ws().heights||={};ws().heights[ws().page+':'+el.dataset.zone+':'+el.dataset.type+':'+el.dataset.index]=el.offsetHeight;persist()}}});
}
function attachDrag(){let drag=null;$$('.tile-header[draggable]').forEach(header=>{header.addEventListener('dragstart',e=>{if(e.target.closest('button')){e.preventDefault();return}const el=header.closest('.tile');drag={zone:el.dataset.zone,index:Number(el.dataset.index),workflow:state.workflow,page:ws().page};e.dataTransfer.setData('application/x-supersurfer-panel',JSON.stringify(drag));e.dataTransfer.effectAllowed='move';header.style.opacity='.5'});header.addEventListener('dragend',()=>{header.style.opacity='';$$('.drag-over').forEach(n=>n.classList.remove('drag-over'));drag=null})});
 $$('[data-zone]').forEach(zone=>{zone.addEventListener('dragover',e=>{if(!arranging||!e.dataTransfer.types.includes('application/x-supersurfer-panel'))return;e.preventDefault();zone.classList.add('drag-over')});zone.addEventListener('dragleave',()=>zone.classList.remove('drag-over'));zone.addEventListener('drop',e=>{if(!arranging||!e.dataTransfer.types.includes('application/x-supersurfer-panel'))return;e.preventDefault();e.stopPropagation();try{const source=JSON.parse(e.dataTransfer.getData('application/x-supersurfer-panel'));if(source.workflow!==state.workflow||source.page!==ws().page)return;const from=source.zone==='sidebar'?ws().sidePanels:ws().pages[ws().page],to=zone.dataset.zone==='sidebar'?ws().sidePanels:ws().pages[ws().page],type=from[source.index];if(!type)return;let target=zone.classList.contains('tile')?Number(zone.dataset.index):to.length;if(from===to&&source.index<target)target--;from.splice(source.index,1);to.splice(target,0,type);render();toast('Panel moved.')}catch{toast('Could not move this panel. Try again.')}})});
}
async function importFiles(files){for(const file of files){if(file.size>20*1024*1024){toast('Demo file limit is 20 MB.');continue}if(file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf')){const old=pdfUrls.get(file.name);if(old)URL.revokeObjectURL(old);pdfUrls.set(file.name,URL.createObjectURL(file));ws().pdfFile=file.name;if(!ws().pages[ws().page].includes('pdf'))ws().pages[ws().page].push('pdf')}else if(file.type.startsWith('text/')||/\.(tex|md|py|json|ya?ml|js|ts|bib|txt|csv|css|html)$/i.test(file.name)){ws().files[file.name]=await file.text();ws().activeFile=file.name;if(!ws().pages[ws().page].includes('editor'))ws().pages[ws().page].unshift('editor')}else{toast('This demo supports PDFs and text/source files.');continue}contexts.push({label:file.name,text:'Imported file: '+file.name});}render();toast('Imported into this demo. PDF uploads stay for this session; text is saved locally.')}
$('#file-input').addEventListener('change',e=>{importFiles([...e.target.files]);e.target.value=''});
document.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('Files')){e.preventDefault();$('#workspace').classList.add('upload-drop')}});document.addEventListener('dragleave',e=>{if(!e.relatedTarget)$('#workspace').classList.remove('upload-drop')});document.addEventListener('drop',e=>{if(e.dataTransfer.files.length){e.preventDefault();$('#workspace').classList.remove('upload-drop');importFiles([...e.dataTransfer.files])}});
render();
