const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function mountEditorConsole(tile,{state,files,path,persist,dialog}){
 const bottom=document.createElement('section');bottom.className='editor-console';bottom.setAttribute('aria-label','Terminal and ports');tile.querySelector('.tile-body').append(bottom);
 const initial=[{kind:'info',text:'Demo terminal · commands are simulated. Type help.'}];
 state.terminalHistory||=initial;state.ports||=[{port:3000,name:'Training dashboard',url:'./project-preview.html',status:'Demo'}];
 function show(tab){state.consoleTab=tab;render();persist()}
 function render(){bottom.hidden=!state.consoleTab;if(bottom.hidden)return;bottom.style.height=(state.consoleHeight||190)+'px';bottom.innerHTML=`<div class="console-resizer" role="separator" aria-label="Resize terminal panel" aria-orientation="horizontal" tabindex="0"></div><div class="console-tabs"><button type="button" data-console-tab="terminal" class="${state.consoleTab==='terminal'?'active':''}">Terminal</button><button type="button" data-console-tab="ports" class="${state.consoleTab==='ports'?'active':''}">Ports <span class="pill">${state.ports.length}</span></button><span class="console-label">${state.consoleTab==='terminal'?'Demo shell':'Demo forwarding'}</span><button type="button" data-console-action="new" title="${state.consoleTab==='terminal'?'New demo terminal':'Forward a sample port'}">＋</button><button type="button" data-console-action="close" title="Close bottom panel" aria-label="Close terminal panel">×</button></div>${state.consoleTab==='terminal'?`<div class="terminal-output" role="log" aria-label="Terminal output">${state.terminalHistory.map(h=>`<div class="terminal-entry-${h.kind}">${escape(h.text)}</div>`).join('')}</div><form class="terminal-input"><span title="${escape(path)}">${escape(path.split('/').at(-1))} $</span><input aria-label="Terminal command" spellcheck="false" autocomplete="off" placeholder="Try pwd, ls, or help"></form>`:`<div class="ports-table"><table><thead><tr><th>Port</th><th>Name</th><th>Address</th><th></th></tr></thead><tbody>${state.ports.map(p=>`<tr><td><i class="port-dot"></i>${p.port}</td><td>${escape(p.name)}</td><td>localhost:${p.port}<span class="port-badge">${escape(p.status)}</span></td><td><a href="${escape(p.url)}" target="_blank" rel="noopener" title="Open sample preview">↗</a><button type="button" data-remove-port="${p.port}" title="Remove sample mapping">×</button></td></tr>`).join('')}</tbody></table><button class="quiet" type="button" data-console-action="forward">＋ Forward a sample port</button><p>Example mappings only. The installed VS Code editor forwards real workspace services.</p></div>`}`;
 bottom.querySelectorAll('[data-console-tab]').forEach(b=>b.onclick=()=>show(b.dataset.consoleTab));
 bottom.querySelector('[data-console-action="close"]').onclick=()=>show(null);
 const resize=bottom.querySelector('.console-resizer');resize.onpointerdown=e=>{e.preventDefault();const start=e.clientY,height=bottom.offsetHeight;resize.setPointerCapture(e.pointerId);resize.onpointermove=ev=>{state.consoleHeight=Math.max(100,Math.min(tile.clientHeight*.7,height+start-ev.clientY));bottom.style.height=state.consoleHeight+'px'};resize.onpointerup=()=>{resize.onpointermove=null;persist()}};resize.onkeydown=e=>{if(['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();state.consoleHeight=Math.max(100,Math.min(tile.clientHeight*.7,(state.consoleHeight||190)+(e.key==='ArrowUp'?20:-20)));bottom.style.height=state.consoleHeight+'px';persist()}};
 if(state.consoleTab==='terminal'){
  const log=bottom.querySelector('.terminal-output');log.scrollTop=log.scrollHeight;
  const form=bottom.querySelector('form');form.onsubmit=e=>{e.preventDefault();const command=form.querySelector('input').value.trim();if(!command)return;state.terminalHistory.push({kind:'command',text:path+' $ '+command});let result;
   if(command==='clear'){state.terminalHistory=[];render();persist();return}
   if(command==='help')result='Available demo commands: pwd, ls, cat <file>, git status, python -m pytest, npm run dev, clear. No shell commands execute on a computer.';
   else if(command==='pwd')result=path;
   else if(command==='ls')result=Object.keys(files).join('  ');
   else if(command.startsWith('cat ')){const name=command.slice(4).trim();result=Object.hasOwn(files,name)?files[name]:'No such demo file: '+name}
   else if(command==='git status')result='Demo workspace: files are saved in this browser. Native Git status is available in the installed editor.';
   else if(command==='python -m pytest'||command==='pytest')result='Example test output (simulated): 2 tests passed. The native terminal runs your actual test suite.';
   else if(command==='npm run dev'){result='Demo dev server at localhost:3000 (simulated). Open the sample page from Ports.';if(!state.ports.some(p=>p.port===3000))state.ports.push({port:3000,name:'Training dashboard',url:'./project-preview.html',status:'Demo'})}
   else result='This demo does not execute arbitrary commands. Type help for supported examples.';
   state.terminalHistory.push({kind:'output',text:result});state.terminalHistory=state.terminalHistory.slice(-100);render();bottom.querySelector('input').focus();persist();
  };
  bottom.querySelector('[data-console-action="new"]').onclick=()=>{state.terminalHistory=[...initial];render();persist()};
 }else{
  const forward=()=>{dialog('Forward a sample port',`<p>This demonstrates the flow. It does not expose a real service.</p><form id="forward-port-form"><input class="dialog-input" name="port" type="number" min="1" max="65535" placeholder="Port, e.g. 5173" required><input class="dialog-input" name="name" maxlength="50" placeholder="Service name"><button class="primary">Add sample mapping</button></form>`);document.querySelector('#forward-port-form').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target),port=Number(data.get('port'));if(!Number.isInteger(port)||port<1||port>65535)return;const entry={port,name:data.get('name').trim()||'Local service',url:'./project-preview.html',status:'Demo'};state.ports=state.ports.filter(p=>p.port!==port).concat([entry]);document.querySelector('#dialog').close();render();persist()}};
  bottom.querySelector('[data-console-action="new"]').onclick=forward;bottom.querySelector('[data-console-action="forward"]').onclick=forward;bottom.querySelectorAll('[data-remove-port]').forEach(b=>b.onclick=()=>{state.ports=state.ports.filter(p=>p.port!==Number(b.dataset.removePort));render();persist()});
 }
 }
 render();return {show};
}
