import {renderDockLayout,dropDock,dockNode,dockRects} from './dock-layout.js';
const canvas=document.querySelector('#layout-demo');
const panels={editor:['main.tex','<pre><span class="command">\\section</span>{Workshop summary and motivation}\n\nWorld models can support planning and policy learning\nfrom video. Robotics adds a practical constraint:\ndecisions must arrive on time.\n\n<span class="command">\\section</span>{Discussion topics}\nWhat information should a model retain for action?\nHow do we measure latency alongside prediction quality?\n\n<span class="command">\\section</span>{Program and deliverables}\nPrepare the schedule, discussion, and workshop website.</pre>'],pdf:['proposal.pdf','<article class="paper-mini"><h3>Real-Time World Models<br>for Robotics</h3><p class="subtitle">Workshop proposal · working draft</p><h4>1. Workshop summary and motivation</h4><p>World models can support planning and policy learning from video. Robotics adds a practical constraint: decisions must arrive on time.</p><h4>2. Discussion topics</h4><p>What information should a model retain for action? How should we measure latency alongside prediction quality?</p></article>'],chat:['Proposal writing worker','<div class="chat-mini"><b>You</b><p>Tighten the motivation and make the real-time constraint explicit.</p><div class="reply"><b>Writing worker</b><p>Keep the proposal focused on decisions that arrive within the robot’s deadline. I’ll revise the motivation and preserve the program scope.</p></div><label>Ask about the selected paragraph… &nbsp; ↑</label></div>']};
for(const [id,[title,body]] of Object.entries(panels)){const el=document.createElement('section');el.className='demo-panel';el.dataset.tileId=id;el.innerHTML=`<header draggable="true"><span>⠿</span><strong>${title}</strong><span>⤢</span></header>${body}`;canvas.append(el);}
let page={tiles:[{id:'editor',span:6},{id:'pdf',span:6}]},drag=null,resize=null,step=0,playing=false,timer;
const states={columns:{axis:'x',ratio:.52,first:{tile:'editor'},second:{tile:'pdf'}},stack:{axis:'x',ratio:.52,first:{axis:'y',ratio:.62,first:{tile:'editor'},second:{empty:true}},second:{tile:'pdf'}},space:{axis:'x',ratio:.6,first:{axis:'y',ratio:.52,first:{tile:'editor'},second:{empty:true}},second:{tile:'pdf'}},fill:{axis:'x',ratio:.6,first:{axis:'y',ratio:.52,first:{tile:'editor'},second:{tile:'chat'}},second:{tile:'pdf'}}};
const captions={columns:'Editor beside a PDF. Start with the work.',stack:'Split one column vertically. Keep the PDF full height.',space:'Resize the divider. Leave room for the next view.',fill:'Drop the conversation into the available space.'};
function layout(name){page={tiles:Object.keys(panels).filter(id=>id!=='chat'||name==='fill').map(id=>({id,span:6})),layout:structuredClone(states[name])};canvas.querySelector('[data-tile-id=chat]').hidden=name!=='fill';renderDockLayout(canvas,page);document.querySelector('#layout-caption').textContent=captions[name];document.querySelectorAll('[data-layout]').forEach(button=>button.classList.toggle('active',button.dataset.layout===name));}
function stop(){playing=false;clearInterval(timer);document.querySelector('#play-layout').textContent='Play layout tour';document.querySelector('#play-layout').setAttribute('aria-pressed','false');}
function start(){
 clearInterval(timer);playing=true;step=0;layout('columns');
 document.querySelector('#play-layout').textContent='Pause layout tour';
 document.querySelector('#play-layout').setAttribute('aria-pressed','true');
 timer=setInterval(()=>{step++;layout(Object.keys(states)[step]);if(step===Object.keys(states).length-1)stop();},3200);
}
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
new IntersectionObserver(entries=>{if(!entries[0].isIntersecting)stop();}).observe(canvas);
canvas.addEventListener('pointerdown',()=>{if(playing)stop();});
document.querySelector('#play-layout').onclick=()=>playing?stop():start();document.querySelectorAll('[data-layout]').forEach(button=>button.onclick=()=>{stop();layout(button.dataset.layout);});
canvas.addEventListener('dragstart',event=>{const tile=event.target.closest('[data-tile-id]');if(!tile)return;stop();drag=tile.dataset.tileId;event.dataTransfer.setData('text/plain',drag);event.dataTransfer.effectAllowed='move';canvas.classList.add('user-manipulating');});canvas.addEventListener('dragover',event=>{if(drag)event.preventDefault();});canvas.addEventListener('drop',event=>{if(!drag)return;event.preventDefault();const target=event.target.closest('[data-tile-id],[data-dock-empty]');if(!target)return;const rect=target.getBoundingClientRect(),x=(event.clientX-rect.left)/rect.width,y=(event.clientY-rect.top)/rect.height,edge=Math.min(x,1-x)<Math.min(y,1-y)?x<.5?'left':'right':y<.5?'top':'bottom';dropDock(page,drag,target.dataset.tileId?{tile:target.dataset.tileId}:{empty:true,path:target.dataset.dockEmpty},edge);renderDockLayout(canvas,page);document.querySelector('#layout-caption').textContent='Your arrangement. Resize a divider, or choose another layout.';});canvas.addEventListener('dragend',()=>{drag=null;canvas.classList.remove('user-manipulating');});
canvas.addEventListener('pointerdown',event=>{const button=event.target.closest('[data-dock-split]');if(!button)return;stop();event.preventDefault();const split=dockRects(page.layout,canvas.clientWidth,canvas.clientHeight).splits.find(row=>row.path===button.dataset.dockSplit);resize={...split,canvas:canvas.getBoundingClientRect()};button.setPointerCapture(event.pointerId);canvas.classList.add('user-manipulating');});canvas.addEventListener('pointermove',event=>{if(!resize)return;const x=resize.node.axis==='x',offset=x?event.clientX-resize.canvas.left-resize.rect.x:event.clientY-resize.canvas.top-resize.rect.y,length=(x?resize.rect.width:resize.rect.height)-8;resize.node.ratio=Math.max(.15,Math.min(.85,offset/length));renderDockLayout(canvas,page);});canvas.addEventListener('pointerup',()=>{resize=null;canvas.classList.remove('user-manipulating');});canvas.addEventListener('keydown',event=>{const button=event.target.closest('[data-dock-split]');if(!button||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key))return;stop();event.preventDefault();const node=dockNode(page.layout,button.dataset.dockSplit);node.ratio=Math.max(.15,Math.min(.85,node.ratio+(['ArrowLeft','ArrowUp'].includes(event.key)?-.04:.04)));renderDockLayout(canvas,page);});new ResizeObserver(()=>renderDockLayout(canvas,page)).observe(canvas);layout('columns');stop();
const presets={writing:{title:'ICLR proposal / Proposal writing',description:'Edit LaTeX, select a paragraph for the agent, and keep the document alongside the source. Keep the program, notes and website tasks on their own pages.',details:[['Source + PDF','Write in the editor and review the document alongside it.'],['Selection → conversation','Attach a passage to chat without pasting a wall of text.'],['More than writing','Add code, a preview and tasks for the workshop website.']]},research:{title:'VLA / E18 — Compare with E12',description:'Compare the E18 learned basis with the E12 PCA-packed baseline, keeping protocol and source identity visible. Inspect overlaid training and validation curves, queue work, and prepare another node when capacity is full.',details:[['Comparable curves','Overlay methods and splits on the same axes.'],['Queue + node readiness','Use prepared nodes first. Onboard alternatives when work is waiting.'],['Persistent monitoring','Keep wakeup triggers and stop criteria visible for each agent.']]},coding:{title:'VLA / Code review — W&B metric logging',description:'Review the worker’s change to the training logger. Keep the source and recorded diff together, accept or reject the patch, and bring selected lines into the conversation.',details:[['Recorded agent changes','Review what the agent changed, alongside the current source.'],['Accept or reject','Decide which edits to keep without losing unrelated work.'],['Editor + terminal + ports','Build a page around the task, with the tools you need.']]}};
const workflowFrame=document.querySelector('#workflow-frame');
let activePreset='writing';
function selectPreset(id,notifyFrame=true){
 if(!Object.hasOwn(presets,id))return;
 const changed=id!==activePreset;activePreset=id;
 const preset=presets[id];
 document.querySelectorAll('[data-preset]').forEach(button=>button.setAttribute('aria-selected',String(button.dataset.preset===id)));
 document.querySelector('#preset-title').textContent=preset.title;
 document.querySelector('#preset-description').textContent=preset.description;
 workflowFrame.title='Interactive '+id+' workflow';
 document.querySelector('#open-workspace').href='playground.html?workflow='+id;
 const details=document.querySelector('#preset-details');
 details.replaceChildren(...preset.details.map(([title,description])=>{const node=document.createElement('div'),b=document.createElement('b'),p=document.createElement('p');b.textContent=title;p.textContent=description;node.append(b,p);return node;}));
 if(changed&&notifyFrame)showWorkflow();
}
function showWorkflow(){workflowFrame.contentWindow?.postMessage({type:'supersurfer-preview-workflow',workflow:activePreset},location.origin);}
workflowFrame.addEventListener('load',showWorkflow);
window.addEventListener('message',event=>{
 if(event.origin!==location.origin||event.source!==workflowFrame.contentWindow)return;
 if(event.data?.type==='supersurfer-preview-ready')showWorkflow();
 if(event.data?.type==='supersurfer-preview-workflow-changed')selectPreset(event.data.workflow,false);
});
document.querySelectorAll('[data-preset]').forEach(button=>button.onclick=()=>selectPreset(button.dataset.preset));
const requested=new URLSearchParams(location.search).get('workflow');if(Object.hasOwn(presets,requested))selectPreset(requested);
