import {validateRange} from './preview-rules.mjs';
const $=s=>document.querySelector(s);
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const metricSpecs=[{key:'action',column:2,title:'Action flow objective'},{key:'dino',column:3,title:'DINO native forecast'},{key:'depth',column:4,title:'Depth native forecast'},{key:'tracks',column:5,title:'Track forecast'}];
let history,records=[],activeMetrics=metricSpecs.map(m=>m.key),range=[0,84850],maxUpdate=84850,expanded=null;
const compact=n=>n>=1000?`${Number((n/1000).toFixed(1))}k`:String(Math.round(n));
const valueText=n=>n>=1?n.toFixed(3):n.toPrecision(4);
function pointsFor(source,metric){return source.rows.filter(r=>Number.isFinite(r[0])&&Number.isFinite(r[metric.column])&&r[metric.column]>0&&r[0]-source.xOffset>=0&&r[0]-source.xOffset<=maxUpdate).map(r=>({x:r[0]-source.xOffset,y:r[metric.column],sourceUpdate:r[0],timestamp:r[1]}));}
function chartMarkup(metric,index){
 const visible=[$('#show-e18').checked,$('#show-e12').checked],log=$('#plot-scale').value==='log',smooth=Number($('#plot-smoothing').value);
 const series=history.sources.map((s,i)=>{let prev;const all=pointsFor(s,metric).map(p=>{prev=prev===undefined?p.y:smooth*prev+(1-smooth)*p.y;return {...p,ema:prev};});return {label:s.label,color:i?'#cc7724':'#2867d9',points:all.filter(p=>p.x>=range[0]&&p.x<=range[1]),visible:visible[i]};});
 const vals=series.filter(s=>s.visible).flatMap(s=>s.points.flatMap(p=>smooth?[p.y,p.ema]:[p.y]));const safe=vals.length?vals:[.001,1];const low=Math.min(...safe),high=Math.max(...safe);
 let lo=log?Math.log10(low*.85):0,hi=log?Math.log10(high*1.1):high*1.07;if(hi<=lo)hi=lo+1;
 const L=65,R=596,T=26,B=272,x=n=>L+(R-L)*(n-range[0])/(range[1]-range[0]),y=n=>B-((log?Math.log10(n):n)-lo)/(hi-lo)*(B-T);
 let ticks=Array.from({length:5},(_,i)=>lo+(hi-lo)*i/4);
 if(log){const candidates=[];for(let power=Math.floor(lo);power<=Math.ceil(hi);power++)for(const multiplier of [1,2,5]){const v=Math.log10(multiplier*10**power);if(v>=lo&&v<=hi)candidates.push({v,multiplier});}if(candidates.length>=2){ticks=candidates.filter(t=>candidates.length<=7||t.multiplier!==2).map(t=>t.v);if(ticks.length>7)ticks=candidates.filter(t=>t.multiplier===1).map(t=>t.v);}}
 const path=(pts,key='y')=>pts.map((p,i)=>`${i?'L':'M'}${x(p.x).toFixed(2)},${y(p[key]).toFixed(2)}`).join(' ');
 const xticks=Array.from({length:5},(_,i)=>range[0]+(range[1]-range[0])*i/4);
 records[index]={series,x,y,L,R,T,B,metric};
 return `<article class="plot-card ${expanded===metric.key?'expanded':''}" data-plot="${index}" data-metric="${metric.key}"><h3>${metric.title}</h3><button class="plot-expand" data-expand="${metric.key}" aria-label="${expanded===metric.key?'Collapse':'Expand'} ${metric.title}" aria-pressed="${expanded===metric.key}">${expanded===metric.key?'↙':'↗'}</button><p>Flow-weighted normalized MSE · training observations</p><svg viewBox="0 0 620 322" tabindex="0" role="img" aria-label="${metric.title}: recorded E18 and E12 loss from ${Math.round(range[0])} to ${Math.round(range[1])} joint updates. Use arrow keys to inspect or drag to zoom."><defs><clipPath id="plot-clip-${index}"><rect x="${L}" y="${T}" width="${R-L}" height="${B-T}"/></clipPath></defs>${ticks.map(v=>{const n=log?10**v:v,py=y(n);return `<line class="gridline" x1="${L}" x2="${R}" y1="${py}" y2="${py}"/><text x="${L-10}" y="${py+4}" text-anchor="end">${n>=.1?Number(n.toPrecision(2)):n.toExponential(1)}</text>`;}).join('')}${xticks.map(v=>`<line class="gridline" x1="${x(v)}" x2="${x(v)}" y1="${T}" y2="${B}"/><text x="${x(v)}" y="${B+20}" text-anchor="middle">${compact(v)}</text>`).join('')}<g clip-path="url(#plot-clip-${index})">${series.filter(s=>s.visible).map(s=>`<path class="chart-line" stroke="${s.color}" opacity="${smooth?.2:.85}" d="${path(s.points)}"/>${smooth?`<path class="chart-line" stroke="${s.color}" d="${path(s.points,'ema')}"/>`:''}`).join('')}</g>${!vals.length?'<text x="330" y="148" text-anchor="middle">No observations in this selection</text>':''}<text x="330" y="316" text-anchor="middle">Joint-codec optimizer updates</text><line class="crosshair" x1="${L}" x2="${L}" y1="${T}" y2="${B}" stroke="#758897" stroke-dasharray="3 4" visibility="hidden"/><rect class="zoom-selection" y="${T}" height="${B-T}" width="0"/><rect class="plot-hit" x="${L}" y="${T}" width="${R-L}" height="${B-T}" fill="transparent"/></svg><div class="chart-tooltip" role="status"></div><span class="plot-count">${series.filter(s=>s.visible).map(s=>`${s.label.split(' · ')[0]}: ${s.points.length.toLocaleString()} observations`).join(' · ')||'Select a run to show its history'}</span></article>`;
}
function renderPlots(){if(!history)return;records=[];$('#real-plots').innerHTML=metricSpecs.filter(m=>activeMetrics.includes(m.key)).map(chartMarkup).join('');
 document.querySelectorAll('.plot-card').forEach((card,i)=>{
 const svg=card.querySelector('svg'),tip=card.querySelector('.chart-tooltip'),line=card.querySelector('.crosshair'),selection=card.querySelector('.zoom-selection');let dragStart=null,keyFraction=.5;
 const fraction=e=>{const r=svg.getBoundingClientRect(),px=(e.clientX-r.left)/r.width*620;return Math.max(0,Math.min(1,(px-65)/(596-65)));};
 const show=(f,screenX)=>{const c=records[i],target=range[0]+f*(range[1]-range[0]);const samples=c.series.filter(s=>s.visible&&s.points.length).map(s=>({...s,point:s.points.reduce((best,p)=>Math.abs(p.x-target)<Math.abs(best.x-target)?p:best,s.points[0])}));if(!samples.length)return;line.setAttribute('x1',c.x(target));line.setAttribute('x2',c.x(target));line.setAttribute('visibility','visible');tip.innerHTML='<span class="tooltip-caption">Nearest recorded observations</span>'+samples.map(s=>`<b style="color:${s.color}">${s.label.split(' · ')[0]}</b> · ${s.point.x.toLocaleString()} updates<br>MSE ${valueText(s.point.y)}${Number($('#plot-smoothing').value)?` · EMA ${valueText(s.point.ema)}`:''}<br>`).join('');tip.classList.add('show');tip.style.left=`${Math.max(4,Math.min(card.clientWidth-242,screenX+12))}px`;tip.style.top='62px';};
 const hide=()=>{line.setAttribute('visibility','hidden');tip.classList.remove('show');};
 svg.addEventListener('pointermove',e=>{const f=fraction(e);if(dragStart!==null){const x1=65+531*dragStart,x2=65+531*f;selection.setAttribute('x',Math.min(x1,x2));selection.setAttribute('width',Math.abs(x2-x1));hide();}else show(f,e.clientX-card.getBoundingClientRect().left);});
 svg.addEventListener('pointerdown',e=>{if(e.button!==0)return;dragStart=fraction(e);svg.setPointerCapture(e.pointerId);});
 svg.addEventListener('pointerup',e=>{if(dragStart===null)return;const end=fraction(e),start=dragStart;dragStart=null;selection.setAttribute('width','0');if(Math.abs(end-start)>.025){const width=range[1]-range[0];setRange(Math.round(range[0]+Math.min(start,end)*width),Math.round(range[0]+Math.max(start,end)*width));}else show(end,e.clientX-card.getBoundingClientRect().left);});
 svg.addEventListener('pointercancel',()=>{dragStart=null;selection.setAttribute('width','0');});svg.addEventListener('pointerleave',()=>{if(dragStart===null)hide();});svg.addEventListener('focus',()=>show(keyFraction,card.clientWidth/2));svg.addEventListener('blur',hide);
 svg.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();keyFraction=e.key==='Home'?0:e.key==='End'?1:Math.max(0,Math.min(1,keyFraction+(e.key==='ArrowRight'?.05:-.05)));show(keyFraction,card.clientWidth*keyFraction);}if(e.key==='Escape')hide();});
 });
 document.querySelectorAll('[data-expand]').forEach(b=>b.onclick=()=>{expanded=expanded===b.dataset.expand?null:b.dataset.expand;renderPlots();});
}
function setRange(start,end){if(!validateRange(start,end,maxUpdate)){$('#range-message').textContent=`Choose a window between 0 and ${maxUpdate.toLocaleString()} updates.`;return;}range=[start,end];$('#range-start').value=Math.round(start);$('#range-end').value=Math.round(end);document.querySelectorAll('[data-range]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.range==='all'?start===0&&end===maxUpdate:start===maxUpdate-20000&&end===maxUpdate)));$('#range-message').textContent='Hover to inspect · drag a plot to zoom';renderPlots();}
$('#apply-range').onclick=()=>setRange(Number($('#range-start').value),Number($('#range-end').value));
for(const id of ['range-start','range-end'])$('#'+id).addEventListener('keydown',e=>{if(e.key==='Enter')$('#apply-range').click();});
document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>setRange(b.dataset.range==='late'?Math.max(0,maxUpdate-20000):0,maxUpdate));
for(const id of ['plot-scale','plot-smoothing','show-e18','show-e12'])$('#'+id).addEventListener('change',renderPlots);
document.addEventListener('preview:metrics',e=>{activeMetrics=e.detail;renderPlots();});
try{const r=await fetch('experiment-data.json');if(!r.ok)throw Error('Snapshot unavailable');history=await r.json();if(history.sources.length!==2||history.sources.some(s=>!s.rows.length))throw Error('Snapshot incomplete');maxUpdate=Math.max(...history.sources[0].rows.map(r=>r[0]-history.sources[0].xOffset));range=[0,maxUpdate];$('#range-end').value=maxUpdate;$('#range-start').max=maxUpdate;$('#range-end').max=maxUpdate;const date=new Date(history.capturedAt);$('#data-date').textContent=`Snapshot · ${date.toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:'UTC'})} UTC`;$('#source-info').innerHTML=history.sources.map(s=>`<div class="source-row"><b>${esc(s.label)}</b><a href="${esc(s.url)}" target="_blank" rel="noopener"><code>${esc(s.runId)}</code> ↗</a><p>${s.rows.length.toLocaleString()} recorded rows · latest observation ${new Date(s.observedAt).toLocaleString('en-US',{timeZone:'UTC'})} UTC<br>X: <code>${esc(s.xKey)}</code>${s.xOffset?` minus ${s.xOffset.toLocaleString()} pretraining updates`:''}</p></div>`).join('');renderPlots();}catch(error){$('#real-plots').innerHTML='<p class="error-note">The recorded data could not load. Reload the preview to try again.</p>';$('#data-date').textContent='Snapshot unavailable';console.error('Experiment snapshot:',error.message);}
