/* Interactive, browser-only configuration. Saving never starts an agent or timer. */
const root = document.querySelector('#surfboard-demo');
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initial = {name:'Experiment worker',model:'Project default',effort:'High',scope:'Selected experiments',views:['Learning curves'],interval:'10',stop:'When the selected runs complete'};
let applied=structuredClone(initial),draft=structuredClone(initial),selected='agent',version=1,notice='Click a block, change its settings, then apply your surfboard.';
const blocks={agent:['01','Experiment worker','Role + model + reasoning'],data:['02','W&B data','Choose comparison inputs'],results:['03','Results','Choose your views'],monitor:['04','Wakeup rule','Trigger + stopping condition']};
const option = (values,current) => values.map(value=>`<option${value===current?' selected':''}>${esc(value)}</option>`).join('');
function fields(){
  if(selected==='agent')return `<label>Role name<input name="name" maxlength="48" value="${esc(draft.name)}" required></label><div class="config-pair"><label>Model<select name="model">${option(['Project default','GPT-6.1 Sol','GPT-6 Astra'],draft.model)}</select></label><label>Reasoning<select name="effort">${option(['Medium','High','Extra high'],draft.effort)}</select></label></div><p>Give each role its own model and effort. The experiment worker stays attached to its task.</p>`;
  if(selected==='data')return `<label>Comparison inputs<select name="scope">${option(['Current experiment','Selected experiments','Project'],draft.scope)}</select></label><div class="config-source-list"><span>◈ E18 · learned basis</span>${draft.scope!=='Current experiment'?'<span>◈ E12 · baseline</span>':''}${draft.scope==='Project'?'<span>◈ Other experiments in VLA</span>':''}</div><p>Choose which experiment sources feed the visualizer. Keep source identities with the comparison.</p>`;
  if(selected==='results')return `<fieldset><legend>Views in your results page</legend>${['Learning curves','Success rates','GPU efficiency','Protocol notes','PDF report'].map(value=>`<label class="config-checkbox"><input type="checkbox" name="views" value="${value}" ${draft.views.includes(value)?'checked':''}>${value}</label>`).join('')}</fieldset><p>A page can combine charts, documents, and custom results. Choose the views that answer your question.</p>`;
  return `<label>Review interval<select name="interval">${['5','10','30','60'].map(value=>`<option value="${value}"${draft.interval===value?' selected':''}>Every ${value} minutes</option>`).join('')}</select></label><label>Stop condition<input name="stop" maxlength="120" value="${esc(draft.stop)}" required></label><p>Define when the worker should check and when to stop. In the app, a saved board is a template; activating a wakeup is a separate action.</p>`;
}
function render(){
 const dirty=JSON.stringify(draft)!==JSON.stringify(applied);
 root.innerHTML=`<div class="config-heading"><div><span class="eyebrow">VLA / Research surfboard</span><h3>Your workflow, down to the details.</h3></div><span class="config-version">Version ${version}${dirty?' · Unsaved changes':''}</span></div><div class="config-body"><div class="config-preview"><div class="config-graph" aria-label="Editable research surfboard">${Object.entries(blocks).map(([id,[number,label,sub]],i)=>`${i?'<span class="config-arrow">→</span>':''}<button data-config-block="${id}" aria-pressed="${selected===id}"><span>${number}</span><b>${id==='agent'?esc(draft.name||label):label}</b><small>${id==='agent'?esc(draft.model):id==='data'?esc(draft.scope):id==='results'?draft.views.length+' view'+(draft.views.length===1?'':'s'):'Every '+draft.interval+' min'}</small></button>`).join('')}</div><div class="config-page-preview"><span class="demo-kicker">YOUR RESULTS PAGE · ${dirty?'DRAFT':'APPLIED'}</span><div class="config-view-chips">${draft.views.length?draft.views.map(view=>`<span>${view==='Learning curves'?'⌁':view==='PDF report'?'▤':'▦'} ${view}</span>`).join(''):'<span class="empty-view">Choose a view in Results to build your page.</span>'}</div><p><b>${esc(draft.name||'Experiment worker')}</b> · ${esc(draft.model)} · ${esc(draft.effort)} reasoning</p><p>Review every ${draft.interval} minutes. Stop: ${esc(draft.stop||'add a stopping condition')}.</p></div><div class="config-presets"><span>Try a change:</span><button data-config-preset="evidence">Add success rates + GPU efficiency</button><button data-config-preset="report">Add a PDF report</button></div></div><form class="config-inspector"><span class="demo-kicker">${blocks[selected][1]} / SETTINGS</span>${fields()}<div class="config-actions"><button type="submit" class="solid-button" ${dirty?'':'disabled'}>Apply surfboard</button><button type="button" data-config-reset>Reset demo</button></div></form></div><div class="config-receipt" role="status">${esc(notice)}</div><div class="config-footnote">Browser preview only. Applying changes here updates the example; it creates no jobs, agents, or schedules.</div>`;
}
function readForm(){
 const form=root.querySelector('form');
 for(const input of form.elements){if(!input.name)continue;if(input.name==='views')continue;draft[input.name]=input.value;}
 if(selected==='results')draft.views=[...form.querySelectorAll('[name=views]:checked')].map(input=>input.value);
}
root.addEventListener('change',event=>{if(!event.target.closest('form')||(event.target.tagName==='INPUT'&&event.target.type!=='checkbox'))return;readForm();render();});
root.addEventListener('input',event=>{if(event.target.tagName!=='INPUT'||event.target.type==='checkbox')return;readForm();root.querySelector('[type=submit]').disabled=JSON.stringify(draft)===JSON.stringify(applied);root.querySelector('.config-version').textContent=`Version ${version} · Unsaved changes`;});
root.addEventListener('click',event=>{
 const button=event.target.closest('button');if(!button)return;
 if(button.dataset.configBlock){readForm();selected=button.dataset.configBlock;render();}
 if(button.hasAttribute('data-config-reset')){draft=structuredClone(initial);applied=structuredClone(initial);version=1;selected='agent';notice='Reset to the original research surfboard.';render();}
 if(button.dataset.configPreset){readForm();const additions=button.dataset.configPreset==='report'?['PDF report']:['Success rates','GPU efficiency'];draft.views=[...new Set([...draft.views,...additions])];selected='results';notice='Preview the added views, then apply the change.';render();}
});
root.addEventListener('submit',event=>{event.preventDefault();readForm();if(!draft.name.trim()||!draft.stop.trim())return;applied=structuredClone(draft);version++;notice=`Version ${version} applied in this preview. ${draft.views.length} result views · ${draft.model} · ${draft.effort} reasoning. No agent or schedule was started.`;render();});
render();
