const $=s=>document.querySelector(s);
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const scenes={
 code:{title:'A real editor, with your extensions.',body:'The VS Code backend is part of the workspace. I use Light Modern and Vim, with Python tooling, a debugger, spell checking, and a point-cloud viewer installed alongside it.',quote:'Vim · Python · Python Debugger · Code Spell Checker · 3D Point Cloud and Mesh Visualizer',label:'Installed in my workspace',result:'The editor works on the project’s real files. The SuperSurfer extension can attach a code selection directly to the agent conversation.',variants:[{id:'editor',label:'VS Code workbench',file:'latex-workspace',alt:'Real VS Code workbench showing main.tex, syntax highlighting, the compiled PDF, and the proposal agent.',focus:[540,240,2160,1280]},{id:'extensions',label:'Installed extensions',file:'vscode-extensions',alt:'Installed extensions in the actual VS Code backend: point-cloud viewer, spell checker, Python, debugger, environments, SuperSurfer, and Vim.',focus:[545,230,2160,1430]}]},
 latex:{title:'Edit the source. Build the paper.',body:'Real main.tex and references.bib, a compiled four-page PDF, and the writing agent beside them. Select the passage that needs work, keep your edits, and review the rendered result.',quote:'“…really about things like video generation world models like cosmos, dreamzero, etc.”',label:'My actual request · October 9',result:'The recorded exchange verifies the bibliography, rebuilds the PDF, checks the rendered pages, and preserves my edits. Source and the matching PDF are then committed together.',variants:[{id:'paper',label:'Source + compiled PDF',file:'latex-workspace',alt:'Actual ICLR proposal with source in VS Code and the compiled four-page PDF in SuperSurfer.',focus:[545,230,2160,1430]}]},
 compute:{title:'Keep experiments moving while you work.',body:'Shared GPU availability, per-project allocations, queued jobs, and a manager that owns launches. Every run keeps its machine, GPU allocation, and experiment identity.',quote:'E18 · orthonormal PCA · 4 GPUs\nE17 · continuation · 4 GPUs\nE16 · microbatch 64 continuation · 2 GPUs',label:'Actual running jobs at capture',result:'This capture has three running jobs and an empty waiting queue. The scheduler exposes queue priority, launch pausing, project limits, and free, busy, reserved, or unknown GPU states.',variants:[{id:'pool',label:'GPU availability',file:'compute',alt:'Actual SuperSurfer compute pool: 169 registered GPUs on 23 nodes, observed availability, and three running jobs.',focus:[530,125,2170,1610]},{id:'runs',label:'Runs & queue controls',file:'runs',alt:'Actual project allocations and E17, E18, and E16 running jobs, with queue priority and pause-launch controls.',focus:[560,510,2080,1350]}]},
 surfboard:{title:'Define how agents are allowed to work.',body:'A Surfboard connects the research lead, worker, implementation, requirements, compute pool, W&B data, visualizer, and wakeups. The layout and the workflow are both yours.',quote:'“Only allow jobs to be launched when mfu is specified”',label:'My actual customization request',result:'My board combines built-in authorization, exact-commit, and verified-PR requirements with explicit MFU guidance for the manager. Monitoring returns to the same experiment worker.',variants:[{id:'graph',label:'Full workflow',file:'surfboard',alt:'Actual E19 research Surfboard connecting lead and worker agents to implementation, requirements, compute, W&B, results, documents, and monitoring.',focus:[1350,960,1880,755]},{id:'requirements',label:'Inspect requirements',file:'surfboard-requirements',alt:'Actual Requirement inspector: User authorization, Exact commit, Verified pr, and MFU guidance.',focus:[1350,945,2400,810]}]}
};
let scene='code',variant='editor',focused=false;
const capture=$('#workspace-capture'),stage=$('#capture-stage');
function currentVariant(){return scenes[scene].variants.find(v=>v.id===variant)||scenes[scene].variants[0];}
function updateFocus(){const v=currentVariant();stage.classList.toggle('focused',focused);stage.style.aspectRatio=focused?`${v.focus[2]}/${v.focus[3]}`:'3840/1986';stage.style.setProperty('--focus-width',`${3840/v.focus[2]*100}%`);stage.style.setProperty('--focus-left',`${-v.focus[0]/v.focus[2]*100}%`);stage.style.setProperty('--focus-top',`${-v.focus[1]/v.focus[3]*100}%`);$('#focus-capture').setAttribute('aria-pressed',String(focused));$('#focus-capture').textContent=focused?'Whole workspace':'Focus view';}
function showScene(next,detail){if(!scenes[next])return;scene=next;variant=detail||scenes[scene].variants[0].id;const s=scenes[scene],v=currentVariant();capture.src=`assets/recorded/${v.file}.jpg`;capture.alt=v.alt;$('#capture-label').textContent=`Recorded ${v.label.toLowerCase()} · Oct 9, 2026`;document.querySelectorAll('.scene-tabs [data-scene]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.scene===scene)));$('#scene-details').innerHTML=`<div><h3>${s.title}</h3><p>${s.body}</p><div class="scene-actions">${s.variants.map(x=>`<button data-variant="${x.id}" aria-pressed="${x.id===v.id}">${x.label}</button>`).join('')}</div></div><div><span class="record-label">${s.label}</span><blockquote>${esc(s.quote).replace(/\n/g,'<br>')}</blockquote><p>${s.result}</p></div>`;updateFocus();}
document.addEventListener('click',event=>{const b=event.target.closest('[data-scene],[data-variant]');if(!b)return;if(b.dataset.scene)showScene(b.dataset.scene,b.dataset.detail);else showScene(scene,b.dataset.variant);});
$('#focus-capture').addEventListener('click',()=>{focused=!focused;updateFocus();});
$('#expand-capture').addEventListener('click',()=>{$('#dialog-title').textContent=`${scenes[scene].title} · recorded workspace`;$('#enlarged-capture').src=capture.src;$('#enlarged-capture').alt=capture.alt;$('#capture-dialog').showModal();});
$('#close-capture').addEventListener('click',()=>$('#capture-dialog').close());
$('#capture-dialog').addEventListener('click',event=>{if(event.target===$('#capture-dialog'))$('#capture-dialog').close();});
const pause=$('#pause-providers');pause.addEventListener('click',()=>{const paused=pause.getAttribute('aria-pressed')!=='true';$('.agent-support').classList.toggle('paused',paused);pause.setAttribute('aria-pressed',String(paused));pause.setAttribute('aria-label',(paused?'Play':'Pause')+' supported-agent banner');pause.textContent=paused?'▷':'Ⅱ';});
showScene('code');

import './research-plots.js';

export function openRecording(which,detail){showScene(which,detail);$('#dialog-title').textContent=`${scenes[scene].title} · original workspace`;$('#enlarged-capture').src=capture.src;$('#enlarged-capture').alt=capture.alt;$('#capture-dialog').showModal();}
