import {ZONE,DATES,dateKey,stamp,state,initialDay,nextItem,minutesUntil,relativeStart} from './time.mjs';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ext=(url,label,cls='')=>`<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener">${esc(label)} <span aria-hidden="true">↗</span></a>`;
const shortDate=d=>new Intl.DateTimeFormat('en-US',{timeZone:ZONE,weekday:'short',month:'short',day:'numeric'}).format(new Date(stamp(d,'12:00')));
const fullDate=d=>new Intl.DateTimeFormat('en-US',{timeZone:ZONE,weekday:'long',month:'long',day:'numeric'}).format(new Date(stamp(d,'12:00')));
const affiliations=s=>{const names=new Map();for(const name of s.split(';').map(x=>x.trim()).filter(Boolean)){const key=name.toLowerCase();if(!names.has(key)||names.get(key)===key)names.set(key,name)}return [...names.values()].join(' · ')};
const naturalName=s=>s.split(';').map(x=>x.trim().split(',').reverse().join(' ').trim()).join(' · ');
let data,items,selected=initialDay(),query='',topic='all',followNow=true;
let expanded=new Set(),pastOpen=new Set();
function badge(s,item,now){return s==='live'?`<span class="status live">Happening now · ${minutesUntil(item.date,item.end,now)} min left</span>`:s==='past'?'<span class="status">Finished</span>':`<span class="status upcoming">${relativeStart(item,now)}</span>`;}
function paperCard(p){return `<article class="paper-card" id="paper-${p.id}">
 <div class="card-top"><span class="topic">${esc(p.topic)}</span><span class="priority ${p.priority===1?'primary':''}">${p.priority===1?'Make time':'Explore'}</span></div>
 <h4>${esc(p.title)}</h4><p class="authors">${esc(naturalName(p.authors))}</p><p class="affiliations">${esc(affiliations(p.affiliations))}</p>
 <div class="poster-location"><div><span class="location-label">POSTER POD</span><strong>${esc(p.pod)}</strong></div><div class="face"><strong>${esc(p.face)} face</strong><span>${esc(p.venue)} · ${p.start}–${p.end}</span></div></div>
 <p class="eyebrow" style="margin-bottom:8px">ABSTRACT SUMMARY</p><p class="card-summary">${esc(p.summary)}</p>
 <div class="card-links">${ext(p.posterUrl,'Find poster','button-link')}${p.projectUrl?ext(p.projectUrl,p.projectLabel,'button-link secondary'):''}${ext(p.sourceUrl,'Paper & abstract','subtle-link')}</div>
 ${!p.projectUrl?'<p class="project-note">Project website not listed in the verified sources.</p>':''}
 <details class="paper-details" data-paper="${p.id}" ${expanded.has(p.id)?'open':''}><summary>Conversation notes <span aria-hidden="true">+</span></summary><div class="details-body"><p class="eyebrow">WHY THIS PAPER</p><p>${esc(p.why)}</p><p class="eyebrow">WORTH ASKING</p><p>${esc(p.question)}</p><p class="oral">Optional oral · ${p.oralTime} · room ${esc(p.oralRoom)}</p></div></details>
 <span class="abstract-label">Abstract summary · paper #${p.id}</span>
 </article>`;}
function eventCard(e,now){return `<article class="event-card ${e.kind==='Workshop posters'?'poster-event':''}" id="event-${e.id}"><div class="card-top"><span class="topic">${esc(e.kind)}</span><span class="priority ${e.recommended?'primary':''}">${e.recommended?'Recommended':'Alternative'}</span></div><h4>${esc(e.title)}</h4><p class="event-location">${e.kind==='Social'?'':'Room '}${esc(e.room)} <span>· ${e.start}–${e.end}</span></p><p>${esc(e.description)}</p>${e.highlights.length?`<details class="event-details"><summary>Program highlights</summary><ul>${e.highlights.map(h=>`<li>${esc(h)}</li>`).join('')}</ul></details>`:''}${ext(e.url,'Organizer program','button-link secondary')}</article>`;}
function matches(p){return (topic==='all'||p.topic===topic)&&[p.title,p.authors,p.summary,p.topic,p.pod,p.why].join(' ').toLowerCase().includes(query.toLowerCase());}
function renderNav(){ $('#day-nav').innerHTML=`<button class="now-button ${followNow?'active':''}" data-now="1">Now & next</button>`+DATES.map((d,i)=>`<button data-day="${d}" class="day-button ${!followNow&&selected===d?'active':''}" ${selected===d?'aria-current="date"':''}><span>${['Mon','Tue','Wed','Thu'][i]}</span><strong>${['28','29','30','01'][i]}</strong></button>`).join('');}
function renderOverview(now){const primary=items.filter(x=>x.kind==='Posters'||x.kind==='Workshop posters'||x.recommended);const live=primary.filter(x=>state(x,now)==='live').sort((a,b)=>(a.kind.includes('posters')?-1:0)-(b.kind.includes('posters')?-1:0));const next=nextItem(primary,now);let a=live[0];let lead=a?`<span class="eyebrow"><i class="live-dot"></i> HAPPENING NOW</span><h2>${esc(a.title)}</h2><p>${a.start}–${a.end} · ${esc(a.room)} · ${minutesUntil(a.date,a.end,now)} min left</p><button class="jump-link" data-jump="${a.id}" data-date="${a.date}">See ${a.kind==='Posters'?'posters':'details'} <span aria-hidden="true">↓</span></button>`:`<span class="eyebrow">${next?'BETWEEN SESSIONS':'CONFERENCE COMPLETE'}</span><h2>${next?'Time for a break.':'Keep the conversations going.'}</h2><p>${next?'Your next recommended session is coming up.':'Browse any day to revisit papers and project links.'}</p>`;
let future=next?`<span class="eyebrow">UP NEXT · ${esc(relativeStart(next,now))}</span><h3>${esc(next.title)}</h3><p>${shortDate(next.date)} · ${next.start}–${next.end} <br> ${esc(next.room)}</p><button class="jump-link" data-jump="${next.id}" data-date="${next.date}">View session <span aria-hidden="true">↓</span></button>`:'<span class="eyebrow">EXPLORE THE PROGRAM</span><h3>37 papers. Four conference days.</h3><p>Paper summaries, poster locations, and project links remain available below.</p>';
$('#live-overview').innerHTML=`<div class="live-panel ${a?'is-live':''}">${lead}${a?`<div class="session-progress" aria-hidden="true"><span style="width:${Math.max(0,Math.min(100,(+now-stamp(a.date,a.start))/(stamp(a.date,a.end)-stamp(a.date,a.start))*100))}%"></span></div>`:''}</div><div class="next-panel">${future}</div>`;
}
function renderTimeline(now=new Date()){
 renderNav();$('#day-date').textContent=selected==='2026-10-01'?'THURSDAY WORKSHOPS & EVENTS':'POSTER-FIRST RESEARCH GUIDE';$('#day-title').textContent=fullDate(selected);
 const ps=data.papers.filter(p=>p.date===selected&&matches(p));$('#result-count').textContent=selected==='2026-10-01'?'5 workshops · 3 poster blocks':`${ps.length} posters`;
 $('#day-note').textContent=selected==='2026-10-01'?'Default: Scalable Infrastructure in the morning, Physical World Models in the afternoon. Other workshops are overlapping alternatives.':'Aim for four or five unhurried conversations per poster window. Pod letters, numbers, and faces below match the official poster map.';
 let sessions=items.filter(x=>x.date===selected).sort((a,b)=>stamp(a.date,a.start)-stamp(b.date,b.start));
 let html=sessions.map(s=>{const posters=s.kind==='Posters'?ps.filter(p=>p.block===s.id):[];if(s.kind==='Posters'&&!posters.length)return '';if(s.kind!=='Posters'&&(topic!=='all'||query)&&![s.title,s.description,s.kind,...(s.highlights||[])].join(' ').toLowerCase().includes(query.toLowerCase()))return '';
 const current=state(s,now),closed=current==='past'&&followNow&&!pastOpen.has(s.id);let body=s.kind==='Posters'?`<p class="section-hint">${posters.length} selected posters · ${s.room} · all locations are poster locations, not talk rooms</p><div class="poster-grid">${posters.sort((a,b)=>a.priority-b.priority||a.pod.localeCompare(b.pod,undefined,{numeric:true})).map(paperCard).join('')}</div>`:eventCard(s,now);
 return `<section class="timeline-row ${current}" id="session-${s.id}"><div class="time-rail"><time datetime="${s.date}T${s.start}:00-04:00">${s.start}</time><span>${s.end}</span><span class="rail-dot" aria-hidden="true"></span></div><div class="session-content"><div class="session-heading"><div><h3>${esc(s.title)}</h3>${badge(current,s,now)}</div>${s.kind==='Posters'?ext('https://2026.ieee-iros.org/program/poster-sessions/','Hall map','map-link'):''}</div>${current==='past'&&followNow?`<details class="past-session" data-session="${s.id}" ${closed?'':'open'}><summary>Browse this earlier session</summary>${body}</details>`:body}</div></section>`}).join('');
 $('#timeline').innerHTML=html||'<div class="empty-state"><h3>No matches on this day.</h3><p>Try another day or clear the search and topic filter.</p><button class="button-link" data-clear="1">Clear filters</button></div>';
}
function tick(){const now=new Date();$('#clock').textContent=new Intl.DateTimeFormat('en-US',{timeZone:ZONE,hour:'numeric',minute:'2-digit',hour12:false}).format(now)+' · Pittsburgh EDT';renderOverview(now);if(followNow&&initialDay(now)!==selected){selected=initialDay(now);renderTimeline(now)}else{document.querySelectorAll('.timeline-row').forEach(el=>{const item=items.find(s=>'session-'+s.id===el.id);const old=['live','past','upcoming'].find(c=>el.classList.contains(c));if(old!==state(item,now)){renderTimeline(now);return}const target=el.querySelector('.status');if(target)target.outerHTML=badge(state(item,now),item,now)})}}
async function init(){try{const response=await fetch(new URL('./data.json',import.meta.url));if(!response.ok)throw Error('data');data=await response.json();items=[...data.blocks.map(b=>({...b,kind:'Posters',title:`${b.time} posters`,room:'Poster Hall',recommended:true})),...data.events];for(const t of [...new Set(data.papers.map(p=>p.topic))].sort()){const option=document.createElement('option');option.value=t;option.textContent=t;$('#topic').append(option)}
 const hash=location.hash.slice(1);if(hash.startsWith('paper-')){const p=data.papers.find(p=>'paper-'+p.id===hash);if(p){selected=p.date;followNow=false;expanded.add(p.id)}}else if(DATES.includes(hash)){selected=hash;followNow=false}
 renderTimeline();tick();if(hash.startsWith('paper-'))document.getElementById(hash)?.scrollIntoView({block:'center'});
 setInterval(tick,30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick()});
 }catch(err){$('#timeline').innerHTML='<div class="empty-state"><h3>The guide could not load.</h3><p>Check your connection and reload, or open the official program linked below.</p><button class="button-link" data-reload="1">Try again</button></div>'}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.reload){location.reload();return}if(!data)return;if(b.dataset.day){selected=b.dataset.day;followNow=false;history.replaceState(null,'','#'+selected);renderTimeline()}else if(b.dataset.now){followNow=true;selected=initialDay();query='';topic='all';$('#search').value='';$('#topic').value='all';history.replaceState(null,'',location.pathname);renderTimeline();const live=items.find(s=>s.date===selected&&state(s)==='live');if(live)document.getElementById('session-'+live.id)?.scrollIntoView({behavior:'smooth',block:'start'})}else if(b.dataset.jump){selected=b.dataset.date;followNow=false;query='';topic='all';$('#search').value='';$('#topic').value='all';renderTimeline();document.getElementById('session-'+b.dataset.jump)?.scrollIntoView({behavior:'smooth',block:'start'})}else if(b.dataset.clear){query='';topic='all';$('#search').value='';$('#topic').value='all';renderTimeline()}else if(b.dataset.reload)location.reload()});
document.addEventListener('toggle',e=>{const p=e.target.dataset?.paper;if(p)e.target.open?expanded.add(p):expanded.delete(p);const s=e.target.dataset?.session;if(s)e.target.open?pastOpen.add(s):pastOpen.delete(s)},true);
$('#search').addEventListener('input',e=>{query=e.target.value;renderTimeline()});$('#topic').addEventListener('change',e=>{topic=e.target.value;renderTimeline()});
init();
